%% Category: bizsequence (2 tables)
erDiagram
    tb_bizsequence {
        int id
        bigint seq
        char_50_ biz
        varchar_8_ bizDesc
        bigint max_seq
        int account_type
        datetime create_time
        datetime update_time
        varchar_255_ operator
    }
    tb_bizsequence_temp {
        varchar_255_ id
        varchar_255_ seq
        varchar_255_ biz
        varchar_255_ bizDesc
        varchar_255_ max_seq
        varchar_255_ account_type
        varchar_255_ create_time
        varchar_255_ update_time
        varchar_255_ operator
    }