%% Category: datascope (1 tables)
erDiagram
    tb_datascope_type {
        int id
        varchar_25_ type_name
        varchar_25_ type_value
        tinyint_1_ is_del
        varchar_25_ oper_user
        datetime oper_time
    }