%% Category: mail (3 tables)
erDiagram
    tb_mail_config {
        bigint id
        varchar_10_ regulator
        varchar_128_ template_invoke_name
        json info
        tinyint_1_ deleted
        varchar_500_ remark
        datetime create_time
        datetime update_time
    }
    tb_mail_info {
        varchar_100_ template_invoke_name
        varchar_255_ subject
        tinyint_1_ deleted
        varchar_500_ remark
        datetime create_time
        datetime update_time
    }
    tb_mail_server {
        int id
        varchar_128_ mail_server_name
        int mail_server_type
        varchar_128_ text_url
        varchar_128_ template_url
        int is_del
        varchar_128_ api_key
    }