%% Category: anti (1 tables)
erDiagram
    tb_anti_attack_history {
        int id
        int user_id
        int detect_type
        varchar_100_ content
        varchar_100_ redis_key
        int status
        int operator_id
        varchar_100_ operator_name
        datetime create_time
        datetime update_time
    }

    %% Cross-category references:
    %% tb_marketing_dashboard_user (external) --> tb_anti_attack_history