%% Category: locale (2 tables)
erDiagram
    tb_locale {
        int id
        varchar_50_ locale
        bit_1_ is_del
    }
    tb_locale_prop {
        int id
        varchar_255_ prop_key
        varchar_255_ prop_value
        int locale_id
        bit_1_ is_del
    }
    tb_locale ||--o{ tb_locale_prop : "has"