%% Category: retail (1 tables)
erDiagram
    tb_retail_source_log {
        int id
        int user_id
        int operate_id
        varchar_255_ operate_user
        varchar_255_ source_type
        varchar_255_ last_source
        varchar_255_ current_source
        varchar_255_ regulator
        datetime create_time
        datetime update_time
        tinyint is_del
    }

    %% Cross-category references:
    %% tb_marketing_dashboard_user (external) --> tb_retail_source_log