%% Category: schedule (1 tables)
erDiagram
    tb_schedule_retry {
        int id
        int task_type
        int task_status
        longtext task_data
        timestamp create_time
        timestamp update_time
    }