%% Category: article (1 tables)
erDiagram
    tb_article_info {
        bigint post_id
        varchar_128_ id
        varchar_10_ language
        varchar_128_ post_type
        varchar_500_ title
        longtext content
        datetime date
        datetime updated
        varchar_100_ author
        varchar_256_ categories
        varchar_512_ tags
        tinyint_1_ is_del
    }