%% Category: mt5 (8 tables)
erDiagram
    mt5_deals_archived_temp {
        int brand
        varchar_150_ DatabaseName
        varchar_32_ brand_name
        bigint_unsigned Deal
        bigint Timestamp
        varchar_32_ ExternalID
        bigint_unsigned Login
        bigint_unsigned Dealer
        bigint_unsigned Order
        int_unsigned Action
        int_unsigned Entry
        int_unsigned Reason
        int_unsigned Digits
        int_unsigned DigitsCurrency
        double ContractSize
        datetime Time
        datetime_6_ TimeMsc
        varchar_32_ Symbol
        double Price
        bigint_unsigned VolumeExt
        double Profit
        double Storage
        double Commission
        double Fee
        double RateProfit
        double RateMargin
        bigint_unsigned ExpertID
        bigint_unsigned PositionID
        varchar_32_ Comment
        double ProfitRaw
        double PricePosition
        double PriceSL
        double PriceTP
        bigint_unsigned VolumeClosedExt
        double TickValue
        double TickSize
        bigint_unsigned Flags
        varchar_16_ Gateway
        double PriceGateway
        int_unsigned ModifyFlags
        double MarketBid
        double MarketAsk
        double MarketLast
        bigint_unsigned Volume
        bigint_unsigned VolumeClosed
        varchar_4000_ ApiData
        double Value
    }
    mt5_symbols {
        varchar_255_ Symbol
    }
    mt5_users_archived_temp {
        int brand
        varchar_150_ DatabaseName
        varchar_32_ brand_name
        bigint_unsigned Login
        bigint Timestamp
        varchar_64_ Group
        bigint_unsigned CertSerialNumber
        bigint_unsigned Rights
        datetime Registration
        datetime LastAccess
        datetime LastPassChange
        varchar_128_ FirstName
        varchar_64_ LastName
        varchar_64_ MiddleName
        varchar_64_ Company
        varchar_32_ Account
        varchar_32_ Country
        int_unsigned Language
        bigint_unsigned ClientID
        varchar_32_ City
        varchar_32_ State
        varchar_16_ ZipCode
        varchar_128_ Address
        varchar_32_ Phone
        varchar_64_ Email
        varchar_32_ ID
        varchar_16_ Status
        varchar_64_ Comment
        int_unsigned Color
        varchar_32_ PhonePassword
        int_unsigned Leverage
        bigint_unsigned Agent
        varchar_128_ TradeAccounts
        double LimitPositions
        int_unsigned LimitOrders
        varchar_32_ LeadCampaign
        varchar_32_ LeadSource
        bigint TimestampTrade
        double Balance
        double Credit
        double InterestRate
        double CommissionDaily
        double CommissionMonthly
        double BalancePrevDay
        double BalancePrevMonth
        double EquityPrevDay
        double EquityPrevMonth
        varchar_256_ Name
        varchar_16_ MQID
        varchar_32_ LastIP
        varchar_4000_ ApiData
    }
    tb_mt5_close {
        bigint_unsigned login
        bigint_unsigned deal_id
        bigint_unsigned ticket
        int_unsigned action
        int_unsigned entry
        varchar_64_ symbol
        bigint_unsigned volume
        datetime close_time
        double credit
        double equity
        double margin
        double balance
        smallint trade_on_credit
        int server
        varchar_255_ comment
        varchar_255_ note
    }
    tb_mt5_margin {
        bigint_unsigned login
        double margin_level
        int account_level_type
        datetime create_time
        datetime update_time
        int server
    }
    tb_mt5_trade {
        bigint_unsigned ticket
        bigint_unsigned login
        varchar_32_ symbol
        int_unsigned digits
        bigint_unsigned volume
        datetime open_time
        double open_price
        double sl
        double tp
        varchar_32_ comment
        double margin_rate
        int_unsigned action
        int_unsigned activation_flags
        int_unsigned activation_mode
        double activation_price
        bigint activation_time
        double contract_size
        bigint_unsigned dealer
        int_unsigned digits_currency
        bigint_unsigned expert_id
        bigint_unsigned expert_position_id
        varchar_32_ external_id
        int_unsigned modification_flags
        double obsolete_value
        varchar_1000_ print
        double rate_profit
        double margin
        double equity
        double credit
        double balance
        tinyint trade_on_credit
        tinyint negative_equity
        int server
        varchar_64_ group
        double bid
        double ask
    }
    tb_mt5_trade_copy1 {
        bigint_unsigned ticket
        bigint_unsigned login
        varchar_32_ symbol
        int_unsigned digits
        bigint_unsigned volume
        datetime open_time
        double open_price
        double sl
        double tp
        varchar_32_ comment
        double margin_rate
        int_unsigned action
        int_unsigned activation_flags
        int_unsigned activation_mode
        double activation_price
        bigint activation_time
        double contract_size
        bigint_unsigned dealer
        int_unsigned digits_currency
        bigint_unsigned expert_id
        bigint_unsigned expert_position_id
        varchar_32_ external_id
        int_unsigned modification_flags
        double obsolete_value
        varchar_1000_ print
        double rate_profit
        double margin
        double equity
        double credit
        double balance
        tinyint trade_on_credit
        tinyint negative_equity
        int server
        varchar_64_ group
        double bid
        double ask
    }
    tb_mt5_trade_copy2 {
        bigint_unsigned ticket
        bigint_unsigned login
        varchar_32_ symbol
        int_unsigned digits
        bigint_unsigned volume
        datetime open_time
        double open_price
        double sl
        double tp
        varchar_32_ comment
        double margin_rate
        int_unsigned action
        int_unsigned activation_flags
        int_unsigned activation_mode
        double activation_price
        bigint activation_time
        double contract_size
        bigint_unsigned dealer
        int_unsigned digits_currency
        bigint_unsigned expert_id
        bigint_unsigned expert_position_id
        varchar_32_ external_id
        int_unsigned modification_flags
        double obsolete_value
        varchar_1000_ print
        double rate_profit
        double margin
        double equity
        double credit
        double balance
        tinyint trade_on_credit
        tinyint negative_equity
        int server
        varchar_64_ group
        double bid
        double ask
    }