%% Category: desensitize (1 tables)
erDiagram
    tb_desensitize_whitelist {
        int_unsigned id
        int rule_category
        varchar_128_ rule_name
        int rule_type
        text whitelist
        int operator_id
        datetime operator_time
        tinyint_1_ online_status
        datetime create_time
        datetime update_time
    }