%% Category: product (1 tables)
erDiagram
    tb_product_trade_data {
        bigint id
        varchar_200_ product_name
        varchar_50_ symbols
        varchar_512_ increase
        datetime the_last_time
        tinyint_1_ is_del
    }