%% Category: bank (1 tables)
erDiagram
    tb_bank_list {
        int id
        varchar_10_ bank_code
        varchar_200_ bank_name
        varchar_10_ branch_code
        varchar_100_ branch_name
    }