%% Category: extra (1 tables)
erDiagram
    tb_extra {
        int user_id
        datetime update_time
        varchar_255_ extra_1
        varchar_255_ extra_2
        varchar_255_ extra_3
    }

    %% Cross-category references:
    %% tb_marketing_dashboard_user (external) --> tb_extra