%% Category: history (1 tables)
erDiagram
    tb_history_data_processing_config {
        int id
        tinyint task_type
        tinyint processing_status
        json process_data
        datetime create_time
        datetime update_time
    }