%% Category: first (1 tables)
erDiagram
    tb_first_login_brand {
        int id
        int user_id
        datetime login_time
        varchar_255_ brand
        varchar_255_ extra_1
        varchar_255_ extra_2
        varchar_255_ extra_3
    }

    %% Cross-category references:
    %% tb_marketing_dashboard_user (external) --> tb_first_login_brand