%% Category: match (2 tables)
erDiagram
    tb_match_group_rule {
        int id
        varchar_1024_ rule
        varchar_64_ group
        tinyint_1_ order
        tinyint_1_ is_del
        datetime create_time
    }
    tb_match_group_rule_backup {
        int id
        varchar_1024_ rule
        varchar_64_ group
        tinyint_1_ order
        tinyint_1_ is_del
        datetime create_time
    }