%% Category: card (70 tables)
erDiagram
    tb_card_account {
        int id
        varchar_100_ wallet_account_no
        varchar_100_ card_account_no
        int user_id
        varchar_64_ cardholder_id
        int status
        int is_del
        int version
        varchar_64_ regulator
        datetime_3_ create_time
        varchar_255_ create_user
        datetime_3_ update_time
        varchar_255_ update_user
    }
    tb_card_apply_channel_audit {
        bigint id
        varchar_64_ cardholder_id
        int user_id
        varchar_64_ apply_record_no
        varchar_64_ channel_flow_no
        varchar_255_ channel_code
        varchar_64_ wallet_account_no
        varchar_64_ channel_Custom_No
        datetime_3_ channel_audit_time
        varchar_64_ international_tel_code
        varchar_64_ tel_no
        varchar_64_ user_email
        int certificate_type
        varchar_64_ country_code
        varchar_64_ fontal_url
        varchar_64_ back_url
        varchar_64_ en_surname
        varchar_64_ en_Name
        int channel_audit_status
        datetime_3_ create_time
        datetime_3_ update_time
    }
    tb_card_apply_channel_reconciliation {
        bigint id
        varchar_64_ channel_code
        date reconciliation_date
        int reconciliation_count
        varchar_10_ reconciliation_currency
        decimal_64_30_ reconciliation_amount
        decimal_64_30_ customers_card_opening_amount_count
        decimal_64_30_ channel_asset_flow_record_amount_count
        int overpayment_order_count
        decimal_64_30_ overpayment_order_amount
        varchar_10_ overpayment_order_currency
        int shortage_order_count
        decimal_64_30_ shortage_order_amount
        varchar_10_ shortage_order_currency
        int pending_reconciliation_order_count
        decimal_64_30_ pending_reconciliation_order_amount
        varchar_10_ pending_reconciliation_order_currency
        int daily_reconciliation_progress
        text daily_reconciliation_fail_desc
        datetime trigger_reconciliation_time
        varchar_255_ remark
        datetime report_generation_time
        datetime create_time
        datetime update_time
    }
    tb_card_apply_channel_reconciliation_record {
        bigint id
        varchar_100_ reconciliation_record_no
        date reconciliation_date
        varchar_100_ apply_record_no
        int user_id
        varchar_100_ wallet_account_no
        tinyint card_type
        tinyint user_type
        bigint business_record_time
        varchar_64_ channel_customer_id
        varchar_64_ channel_apply_order_no
        decimal_64_30_ channel_apply_fee_amount
        varchar_64_ channel_apply_fee_currency
        tinyint channel_audit_status
        decimal_64_30_ customers_card_opening_amount
        bigint channel_apply_time
        bigint channel_finish_time
        varchar_64_ card_channel_zone_id
        datetime platform_finish_time
        bigint asset_flow_record_id
        int asset_flow_record_card_pool_id
        int asset_flow_record_vendor_card_id
        varchar_255_ asset_flow_record_vendor_order_no
        varchar_255_ asset_flow_record_client_order_no
        decimal_64_30_ asset_flow_record_amount
        int asset_flow_record_item_id
        varchar_64_ asset_flow_record_item_currency
        int asset_flow_record_direction
        bigint asset_flow_record_create_time
        tinyint reconciliation_status
        tinyint reconciliation_result_type
        varchar_64_ regulator
        datetime create_time
        datetime update_time
    }
    tb_card_apply_record {
        bigint id
        varchar_100_ apply_record_no
        varchar_64_ cardholder_id
        int user_id
        varchar_100_ wallet_account_no
        varchar_64_ channel_customer_id
        varchar_64_ channel_apply_order_no
        decimal_64_30_ channel_apply_fee_amount
        varchar_64_ channel_apply_fee_currency
        bigint channel_apply_time
        bigint channel_finish_time
        varchar_64_ card_product_code
        tinyint card_type
        tinyint card_level
        tinyint real_card_level
        varchar_20_ user_vip_level
        varchar_40_ referral_code
        tinyint referral_code_status
        tinyint user_type
        varchar_10_ phone_area_code
        varchar_256_ phone_number
        tinyint phone_status
        varchar_256_ email_addr
        tinyint email_status
        tinyint two_factor_auth_status
        tinyint user_kyc_level
        varchar_10_ nationality_code
        tinyint id_type
        varchar_64_ id_number
        varchar_2_ id_issuing_country
        datetime_3_ id_issue_date
        datetime_3_ id_expiry_date
        varchar_100_ id_card_front_img
        varchar_100_ id_card_back_img
        varchar_64_ first_name
        varchar_64_ middle_name
        varchar_64_ last_name
        varchar_256_ user_name
        tinyint gender
        varchar_64_ birthday
        tinyint poi_audit_status
        tinyint pof_audit_status
        varchar_2_ residence_country
        varchar_255_ residence_region
        varchar_255_ residence_city
        varchar_500_ residence_street
        varchar_500_ residence_building
        varchar_50_ residence_postal_code
        tinyint poa_audit_status
        varchar_64_ application_id
        tinyint apply_status
        tinyint channel_audit_status
        varchar_64_ protocol_version
        datetime_3_ finish_time
        varchar_255_ note
        tinyint is_deleted
        int version
        varchar_64_ regulator
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
    }
    tb_card_balance_record {
        bigint id
        varchar_255_ channel_code
        varchar_4000_ data
        bigint timestamp
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    tb_card_bin_record {
        int id
        varchar_20_ regulator_name
        varchar_20_ scenario
        varchar_20_ bin_no
        varchar_50_ user_id
        varchar_100_ card_brand
        varchar_100_ card_type
        varchar_100_ card_issuing_bank
        varchar_20_ card_issuing_country
        tinyint is_in_blacklist
        varchar_20_ error_code
        varchar_255_ message
        datetime create_time
        datetime update_time
    }
    tb_card_black_list {
        int id
        int user_id
        varchar_50_ card_id
        json description
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
        int version
    }
    tb_card_channel {
        bigint id
        varchar_64_ channel_code
        varchar_64_ channel_name
        varchar_32_ channel_alias
        varchar_512_ description
        tinyint fund_mode
        varchar_12_ settlement_currency
        varchar_12_ crypto_backed
        varchar_128_ server_domain
        tinyint server_status
        tinyint status
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
        varchar_12_ update_user
        int version
        varchar_64_ fingerprint
    }
    tb_card_channel_country_blacklist {
        bigint id
        varchar_64_ channel_code
        varchar_128_ product_code
        varchar_64_ country_id
        varchar_128_ country_name
        varchar_128_ country_name_cn
        varchar_64_ iso_code
        varchar_64_ calling_code
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
        varchar_12_ update_user
    }
    tb_card_channel_request_log {
        bigint id
        varchar_64_ event_id
        varchar_64_ channel_code
        varchar_64_ trade_order_no
        varchar_1024_ request_url
        datetime_3_ request_time
        mediumtext request_body
        datetime_3_ response_time
        mediumtext response
        int status
        varchar_64_ direction
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
    }
    tb_card_charging_scheme {
        bigint id
        varchar_64_ product_code
        varchar_64_ scheme_code
        varchar_64_ scheme_name
        int scheme_version
        varchar_64_ payment_type
        tinyint status
        datetime executing_start_time
        datetime executing_end_time
        tinyint executing_status
        int priority
        varchar_1000_ notes
        tinyint history
        varchar_64_ operation
        varchar_255_ operative
        int version
        varchar_255_ fingerprint
        varchar_255_ create_user
        datetime create_time
        varchar_255_ update_user
        datetime update_time
    }
    tb_card_charging_scheme_purchase {
        bigint id
        varchar_64_ product_code
        varchar_64_ scheme_code
        varchar_64_ scheme_name
        int scheme_version
        text card_id
        varchar_64_ mcc
        decimal_64_30_ payment_min_amount
        decimal_64_30_ payment_max_amount
        decimal_64_30_ vendor_domestic_payment_rate
        decimal_64_30_ vcard_domestic_payment_markup
        decimal_64_30_ vcard_domestic_payment_rate
        decimal_64_30_ vendor_cross_border_payment_rate
        decimal_64_30_ vcard_cross_border_payment_markup
        decimal_64_30_ vcard_cross_border_payment_rate
        decimal_64_30_ vendor_domestic_fixed_charge_payment_fee
        decimal_64_30_ vcard_domestic_fixed_charge_payment_markup
        decimal_64_30_ vcard_domestic_fixed_charge_payment_fee
        decimal_64_30_ vendor_cross_border_fixed_charge_payment_fee
        decimal_64_30_ vcard_cross_border_fixed_charge_payment_markup
        decimal_64_30_ vcard_cross_border_fixed_charge_payment_fee
        decimal_64_30_ three_ds_forwarding_fee
        decimal_64_30_ three_ds_frictionless_fee
        varchar_255_ fiat_exchange_from
        varchar_255_ fiat_exchange_to
        decimal_64_30_ fiat_exchange_markup
        varchar_255_ stable_coin_exchange_from
        varchar_255_ stable_coin_exchange_to
        decimal_64_30_ stable_coin_exchange_markup
        decimal_64_30_ vcard_exchange_rate
        int version
        varchar_255_ fingerprint
        varchar_255_ create_user
        datetime create_time
        varchar_255_ update_user
        datetime update_time
    }
    tb_card_charging_scheme_refund {
        bigint id
        varchar_64_ product_code
        varchar_64_ scheme_code
        varchar_64_ scheme_name
        int scheme_version
        text card_id
        varchar_64_ mcc
        decimal_64_30_ refund_min_amount
        decimal_64_30_ refund_max_amount
        tinyint refund_payment_fee_status
        decimal_64_30_ vendor_domestic_refund_rate
        decimal_64_30_ vcard_domestic_refund_markup
        decimal_64_30_ vcard_domestic_refund_rate
        decimal_64_30_ vendor_cross_border_refund_rate
        decimal_64_30_ vcard_cross_border_refund_markup
        decimal_64_30_ vcard_cross_border_refund_rate
        decimal_64_30_ vendor_domestic_fixed_charge_refund_fee
        decimal_64_30_ vcard_domestic_fixed_charge_refund_markup
        decimal_64_30_ vcard_domestic_fixed_charge_refund_fee
        decimal_64_30_ vendor_cross_border_fixed_charge_refund_fee
        decimal_64_30_ vcard_cross_border_fixed_charge_refund_markup
        decimal_64_30_ vcard_cross_border_fixed_charge_refund_fee
        int version
        varchar_255_ fingerprint
        varchar_255_ create_user
        datetime create_time
        varchar_255_ update_user
        datetime update_time
    }
    tb_card_country_whitelist {
        bigint id
        varchar_64_ country_id
        varchar_128_ country_name
        varchar_64_ country_code
        varchar_128_ channel_name
        varchar_64_ channel_code
        varchar_128_ product_name
        varchar_64_ product_code
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
        varchar_12_ update_user
    }
    tb_card_customer_info {
        bigint id
        varchar_64_ customer_id
        varchar_64_ cardholder_id
        varchar_40_ referral_code
        int user_id
        tinyint user_type
        varchar_100_ wallet_account_no
        varchar_64_ channel_customer_id
        tinyint channel_audit_status
        varchar_10_ phone_area_code
        varchar_256_ phone_number
        tinyint phone_status
        varchar_256_ email_addr
        tinyint email_status
        tinyint two_factor_auth_status
        tinyint user_kyc_level
        varchar_10_ nationality_code
        tinyint id_type
        varchar_64_ id_number
        varchar_2_ id_issuing_country
        varchar_64_ first_name
        varchar_64_ middle_name
        varchar_64_ last_name
        varchar_256_ user_name
        tinyint gender
        varchar_64_ birthday
        datetime_3_ id_issue_date
        datetime_3_ id_expiry_date
        varchar_100_ id_card_front_img
        varchar_100_ id_card_back_img
        tinyint poi_audit_status
        tinyint pof_audit_status
        varchar_2_ residence_country
        varchar_255_ residence_region
        varchar_255_ residence_city
        varchar_500_ residence_street
        varchar_500_ residence_building
        varchar_50_ residence_postal_code
        tinyint poa_audit_status
        varchar_64_ application_id
        varchar_100_ supplement_name
        text supplement_content
        datetime_3_ supplement_time
        text supplement_note
        varchar_256_ supplement_by
        varchar_100_ device_id
        tinyint is_frictionless
        datetime_3_ frictionless_cycle_recycle_time
        int frictionless_pop_up_count
        tinyint is_faceId_enabled
        varchar_255_ is_touchId_enabled
        int version
        tinyint is_deleted
        varchar_64_ regulator
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
        text protocol_version
        varchar_255_ external_channel_consumer_id
        varchar_255_ wallet_acount_status
    }
    tb_card_customer_whitelist {
        bigint id
        bigint user_id
        varchar_64_ user_name
        varchar_64_ wallet_account_no
        varchar_128_ channel_name
        varchar_64_ channel_code
        varchar_64_ product_code
        varchar_128_ product_name
        varchar_64_ national
        varchar_64_ country_id
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
        varchar_12_ update_user
    }
    tb_card_file_upload_record {
        bigint id
        bigint file_id
        tinyint status
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_255_ serial_no
        int version
        varchar_255_ file_path
    }
    tb_card_history {
        bigint id
        varchar_64_ biz_code
        varchar_12_ biz_type
        varchar_12_ operation_type
        text before
        text after
        varchar_64_ ip_address
        varchar_1024_ remarks
        int version
        datetime_3_ create_time
        varchar_64_ create_user
    }
    tb_card_info {
        bigint id
        varchar_100_ apply_record_no
        bigint user_id
        varchar_64_ card_product_code
        varchar_64_ cardholder_id
        varchar_100_ wallet_account_no
        varchar_100_ card_account_no
        varchar_64_ card_no
        varchar_64_ card_id
        int channel_card_id
        int card_type
        tinyint card_level
        tinyint card_apply_level
        tinyint card_status
        tinyint shipping_status
        tinyint is_bind_card_pool
        datetime_3_ active_time
        int card_valid_month
        varchar_20_ currency_code
        varchar_256_ public_token
        varchar_256_ emboss_name
        varchar_256_ masked_pan
        bigint region_id
        varchar_64_ region_name
        bigint country_id
        varchar_256_ country_name
        varchar_20_ pin
        tinyint is_first_pay
        tinyint is_issue_benefits
        tinyint is_deleted
        int version
        varchar_255_ fingerprint
        varchar_64_ regulator
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
    }
    tb_card_ip_risk {
        varchar_64_ id
        varchar_64_ ip_address
        int confidence
        datetime created
        varchar_64_ created_by_ref
        varchar_5000_ description
        varchar_64_ ext_extension_type
        datetime ext_created_at
        varchar_64_ ext_created_by_ref_id
        text ext_creator_ids
        tinyint_1_ ext_detection
        varchar_64_ ext_id
        tinyint_1_ ext_is_inferred
        text ext_labels_ids
        varchar_64_ ext_main_observable_type
        varchar_64_ ext_observable_type
        text ext_observable_value
        int ext_score
        varchar_64_ ext_type
        datetime ext_updated_at
        text labels
        varchar_64_ lang
        datetime modified
        varchar_64_ name
        varchar_256_ pattern
        varchar_64_ pattern_type
        varchar_64_ pattern_version
        tinyint_1_ revoked
        varchar_64_ spec_version
        varchar_64_ type
        datetime valid_from
        datetime valid_until
        datetime created_date
        datetime updated_date
    }
    tb_card_kyc_info_history {
        bigint id
        bigint user_id
        int user_type
        varchar_255_ real_name
        varchar_255_ first_name
        varchar_255_ middle_name
        varchar_255_ last_name
        varchar_50_ gender
        varchar_100_ nationality
        varchar_100_ country_of_residence
        varchar_20_ phone_code
        varchar_50_ phone
        varchar_50_ nationality_country_code
        varchar_50_ date_birth
        int email_verify_status
        int phone_verify_status
        tinyint_1_ two_fa_verify_status
        int level
        int poi_verify_status
        int id_type
        varchar_255_ id_number
        datetime poi_issued_date
        varchar_255_ email
        datetime poi_valid_until
        varchar_2000_ file_ids
        int pof_verify_status
        int poa_verify_status
        int country_id
        varchar_255_ suburb
        varchar_500_ address
        varchar_255_ state
        varchar_50_ postcode
        tinyint_1_ aml_check
        tinyint_1_ poa_is_verify
        tinyint_1_ pof_is_verify
        int kyc_origin
        varchar_255_ first_name_en
        varchar_255_ last_name_en
        varchar_255_ middle_name_en
        varchar_255_ client_name_en
        varchar_64_ application_id
        tinyint sumsub_type
        datetime_3_ create_time
    }
    tb_card_mcc {
        bigint id
        bigint consumption_categories
        varchar_255_ consumption_categories_des
        bigint mcc_code
        varchar_255_ mcc_title
        varchar_255_ mcc_en
        datetime_3_ create_time
    }
    tb_card_message_notify {
        bigint id
        bigint user_id
        varchar_64_ card_id
        varchar_64_ message_key
        int status
        int operation_style
        int content_status
        varchar_255_ create_user
        datetime create_time
        varchar_255_ update_user
        datetime update_time
    }
    tb_card_operation_record {
        bigint id
        int user_id
        varchar_64_ card_id
        tinyint card_type
        varchar_64_ card_no
        tinyint operation_type
        tinyint operation_style
        int reason
        varchar_256_ note
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
    }
    tb_card_payment_limit {
        bigint id
        varchar_64_ limit_manage_id
        int card_level
        int country_type
        int payment_type
        int scheme_status
        int executing_status
        varchar_32_ currency_code
        decimal_64_30_ min_per_pay_amount
        decimal_64_30_ max_per_pay_amount
        decimal_64_30_ daily_max_cume_amount
        decimal_64_30_ monthly_max_cume_amount
        decimal_64_30_ annually_max_cume_amount
        datetime effective_time
        datetime expired_time
        int version
        int operation_type
        tinyint history
        varchar_255_ fingerprint
        int is_deleted
        varchar_255_ create_user
        datetime create_time
        varchar_255_ update_user
        datetime update_time
    }
    tb_card_payment_limit_card_map {
        bigint id
        varchar_64_ limit_manage_id
        bigint limit_id
        varchar_64_ card_id
        int is_deleted
        varchar_255_ create_user
        datetime create_time
        varchar_255_ update_user
        datetime update_time
    }
    tb_card_payment_limit_country_map {
        bigint id
        varchar_64_ limit_manage_id
        bigint limit_id
        int country_id
        int is_deleted
        varchar_255_ create_user
        datetime create_time
        varchar_255_ update_user
        datetime update_time
    }
    tb_card_pricing {
        bigint id
        varchar_64_ product_code
        varchar_64_ pricing_code
        varchar_64_ tier_cover
        decimal_64_30_ issuance_fee
        decimal_64_30_ management_fee
        tinyint charging_cycle
        decimal_64_30_ cancellation_fee
        tinyint first_year_fee_waived
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
        varchar_12_ update_user
        int version
        varchar_64_ fingerprint
    }
    tb_card_product {
        bigint id
        varchar_64_ channel_code
        varchar_64_ product_code
        varchar_64_ card_bin
        varchar_64_ product_name
        varchar_512_ description
        tinyint card_type
        varchar_64_ tier_cover
        varchar_32_ scheme
        varchar_32_ area
        varchar_32_ country
        varchar_32_ country_code
        varchar_32_ currency
        varchar_32_ currency_code
        int validity_period
        datetime_3_ start_date
        datetime_3_ end_date
        tinyint need_activate
        int enable_fiat_to_usdt
        tinyint status
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
        varchar_12_ update_user
        int version
        varchar_64_ fingerprint
    }
    tb_card_product_payment_type {
        bigint id
        varchar_64_ product_code
        bigint product_version
        varchar_64_ payment_type
        tinyint current_value
        tinyint pending_value
        datetime_3_ effective_time
        datetime_3_ expiry_time
        int version
        tinyint status
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
    }
    tb_card_purchase_channel_order {
        bigint id
        varchar_64_ purchase_record_no
        varchar_64_ channel_order_no
        int user_id
        decimal_64_30_ channel_local_amount
        varchar_20_ channel_local_currency
        decimal_64_30_ basic_service_rate
        decimal_64_30_ basic_service_fee
        decimal_64_30_ cross_border_rate
        decimal_64_30_ cross_border_fee
        decimal_64_30_ cross_border_fixed_fee
        decimal_64_30_ other_fees
        decimal_64_30_ total_fee
        varchar_64_ fee_currency
        decimal_64_30_ frozen_amount
        varchar_64_ frozen_currency
        decimal_64_30_ deduct_amount
        varchar_64_ deduct_currency
        bigint authorized_time
        bigint authorized_finish_time
        bigint bill_id
        tinyint bill_type
        int version
        varchar_64_ fingerprint
        varchar_12_ create_user
        datetime_3_ create_time
    }
    tb_card_purchase_channel_pending_recon_snap {
        bigint id
        varchar_100_ reconciliation_record_no
        date reconciliation_date
        varchar_100_ trade_order_no
        varchar_100_ purchase_record_no
        varchar_64_ benefits_order_no
        varchar_64_ channel_order_no
        varchar_64_ wallet_convert_trade_order_no
        varchar_100_ platform_card_id
        bigint business_record_time
        varchar_64_ card_no
        varchar_255_ wallet_account_no
        tinyint purchase_status
        varchar_64_ user_merchant_id
        int user_id
        varchar_255_ user_merchant_code
        decimal_64_30_ original_order_amount
        varchar_100_ original_order_currency
        decimal_64_30_ payment_amount
        varchar_64_ payment_currency
        datetime_3_ authorized_time
        decimal_64_30_ authorized_amount
        varchar_64_ authorized_currency
        decimal_64_30_ frozen_amount
        varchar_64_ frozen_currency
        decimal_64_30_ benefits_amount
        varchar_64_ benefits_currency
        decimal_64_30_ deduct_amount
        varchar_64_ deduct_currency
        decimal_64_30_ fee_amount
        varchar_64_ fee_currency
        decimal_64_30_ rebates_amount
        varchar_64_ rebates_currency
        datetime_3_ deduct_time
        varchar_100_ charging_scheme_code
        decimal_64_30_ base_fee_rate_pct
        decimal_64_30_ base_fee_amount
        varchar_100_ base_fee_currency
        decimal_64_30_ base_small_fixed_fee_amount
        varchar_100_ base_small_fixed_fee_currency
        decimal_64_30_ cross_border_fee_rate_pct
        decimal_64_30_ cross_border_fee_amount
        varchar_100_ cross_border_fee_currency
        decimal_64_30_ cross_border_small_fixed_fee_amount
        varchar_100_ cross_border_small_fixed_fee_currency
        decimal_64_30_ fx_fee_rate_pct
        decimal_64_30_ fx_fee_amount
        varchar_100_ fx_fee_currency
        decimal_64_30_ other_fee
        bigint bill_record_id
        varchar_255_ card_channel_bill_vendor_order_no
        varchar_255_ card_channel_bill_client_order_no
        bigint card_channel_bill_trade_time
        bigint card_channel_bill_trade_begin_time
        varchar_255_ card_channel_bill_fee
        varchar_255_ card_channel_bill_usdt_amount
        varchar_255_ card_channel_bill_reconciliation_currency
        tinyint card_channel_bill_status
        bigint card_channel_id
        varchar_100_ card_channel_code
        varchar_100_ card_channel_name
        varchar_64_ card_channel_zone_id
        decimal_64_30_ card_channel_capture_amount
        varchar_64_ card_channel_capture_currency
        varchar_64_ card_channel_capture_batch
        datetime_3_ card_channel_capture_time
        tinyint card_channel_authorized_status
        decimal_64_30_ card_channel_local_amount
        varchar_20_ card_channel_local_currency
        decimal_64_30_ card_channel_basic_service_rate
        decimal_64_30_ card_channel_basic_service_fee
        varchar_100_ card_channel_base_fee_currency
        decimal_64_30_ card_channel_cross_border_rate
        decimal_64_30_ card_channel_cross_border_fee
        decimal_64_30_ card_channel_cross_border_fixed_fee
        decimal_64_30_ card_channel_other_fees
        decimal_64_30_ card_channel_total_fee
        varchar_64_ card_channel_fee_currency
        decimal_64_30_ card_channel_frozen_amount
        varchar_64_ card_channel_frozen_currency
        decimal_64_30_ card_channel_deduct_amount
        varchar_64_ card_channel_deduct_currency
        bigint card_channel_authorized_time
        bigint card_channel_authorized_finish_time
        bigint card_channel_bill_id
        tinyint card_channel_bill_type
        varchar_64_ wallet_adjustment_trade_order_no
        decimal_64_30_ adjust_amount_usd
        decimal_64_30_ adjust_amount
        varchar_100_ adjust_currency
        varchar_50_ wallet_trade_order_no
        tinyint wallet_trade_direction
        varchar_100_ wallet_from_account_no
        varchar_100_ wallet_from_account_name
        tinyint wallet_from_account_type
        varchar_20_ wallet_from_currency_no
        varchar_20_ wallet_from_currency_code
        decimal_64_30_ wallet_from_amt
        varchar_100_ wallet_to_account_no
        varchar_100_ wallet_to_account_name
        tinyint wallet_to_account_type
        varchar_20_ wallet_to_currency_no
        varchar_20_ wallet_to_currency_code
        decimal_64_30_ wallet_to_amt
        decimal_64_30_ wallet_exchange_rate
        decimal_64_30_ wallet_fee_rate
        varchar_20_ wallet_fee_currency_no
        varchar_20_ wallet_fee_currency_code
        decimal_64_30_ wallet_fee_amt
        varchar_50_ benefits_trade_order_no
        tinyint benefits_trade_direction
        varchar_100_ benefits_from_account_no
        varchar_100_ benefits_from_account_name
        tinyint benefits_from_account_type
        varchar_20_ benefits_from_currency_no
        varchar_20_ benefits_from_currency_code
        decimal_64_30_ benefits_from_amt
        varchar_100_ benefits_to_account_no
        varchar_100_ benefits_to_account_name
        tinyint benefits_to_account_type
        varchar_20_ benefits_to_currency_no
        varchar_20_ benefits_to_currency_code
        decimal_64_30_ benefits_to_amt
        decimal_64_30_ benefits_exchange_rate
        decimal_64_30_ benefits_fee_rate
        varchar_20_ benefits_fee_currency_no
        varchar_20_ benefits_fee_currency_code
        decimal_64_30_ benefits_fee_amt
        varchar_50_ rebates_trade_order_no
        tinyint rebates_trade_direction
        varchar_100_ rebates_from_account_no
        varchar_100_ rebates_from_account_name
        tinyint rebates_from_account_type
        varchar_20_ rebates_from_currency_no
        varchar_20_ rebates_from_currency_code
        decimal_64_30_ rebates_from_amt
        varchar_100_ rebates_to_account_no
        varchar_100_ rebates_to_account_name
        tinyint rebates_to_account_type
        varchar_20_ rebates_to_currency_no
        varchar_20_ rebates_to_currency_code
        decimal_64_30_ rebates_to_amt
        decimal_64_30_ rebates_exchange_rate
        decimal_64_30_ rebates_fee_rate
        varchar_20_ rebates_fee_currency_no
        varchar_20_ rebates_fee_currency_code
        decimal_64_30_ rebates_fee_amt
        decimal_64_30_ flat_exchange_rate_gain_loss
        varchar_100_ flat_exchange_rate_gain_loss_currency
        decimal_64_30_ crypto_exchange_rate_gain_loss
        varchar_100_ crypto_exchange_rate_gain_loss_currency
        decimal_64_30_ crypto_hedge_profit_amount
        varchar_100_ crypto_hedge_profit_currency_currency
        decimal_64_30_ crypto_hedge_loss_amount
        varchar_100_ crypto_hedge_loss_currency_currency
        tinyint reconciliation_status
        tinyint reconciliation_result_type
        tinyint inner_reconciliation_result_type
        varchar_255_ remark
        varchar_64_ regulator
        datetime create_time
        datetime update_time
    }
    tb_card_purchase_channel_reconciliation {
        bigint id
        varchar_64_ channel_code
        date reconciliation_date
        int reconciliation_count
        varchar_10_ reconciliation_currency
        decimal_64_30_ reconciliation_amount
        decimal_64_30_ channel_cost_amount
        varchar_10_ channel_cost_currency
        decimal_64_30_ platform_fee_income_amount
        varchar_10_ platform_fee_income_currency
        decimal_64_30_ crypto_hedge_profit_amount
        varchar_10_ crypto_hedge_profit_currency
        decimal_64_30_ crypto_hedge_loss_amount
        varchar_10_ crypto_hedge_loss_currency
        int overpayment_order_count
        decimal_64_30_ overpayment_order_amount
        varchar_10_ overpayment_order_currency
        int shortage_order_count
        decimal_64_30_ shortage_order_amount
        varchar_10_ shortage_order_currency
        int pending_reconciliation_order_count
        decimal_64_30_ pending_reconciliation_order_amount
        varchar_10_ pending_reconciliation_order_currency
        decimal_64_30_ pending_reconciliation_channel_cost_amount
        varchar_10_ pending_reconciliation_channel_cost_currency
        decimal_64_30_ pending_reconciliation_platform_fee_income_amount
        varchar_10_ pending_reconciliation_platform_fee_income_currency
        decimal_64_30_ pending_reconciliation_crypto_hedge_profit_amount
        varchar_10_ pending_reconciliation_crypto_hedge_profit_currency
        decimal_64_30_ pending_reconciliation_crypto_hedge_loss_amount
        varchar_10_ pending_reconciliation_crypto_hedge_loss_currency
        int daily_reconciliation_progress
        text daily_reconciliation_fail_desc
        tinyint cps_sync_status
        tinyint snap_sync_status
        datetime trigger_reconciliation_time
        varchar_255_ remark
        datetime report_generation_time
        datetime create_time
        datetime update_time
    }
    tb_card_purchase_channel_reconciliation_record {
        bigint id
        varchar_100_ reconciliation_record_no
        date reconciliation_date
        varchar_100_ trade_order_no
        varchar_100_ purchase_record_no
        varchar_64_ benefits_order_no
        varchar_64_ channel_order_no
        varchar_64_ wallet_convert_trade_order_no
        varchar_100_ platform_card_id
        bigint business_record_time
        varchar_64_ card_no
        varchar_64_ wallet_account_no
        tinyint purchase_status
        varchar_64_ user_merchant_id
        int user_id
        varchar_255_ user_merchant_code
        decimal_64_30_ original_order_amount
        varchar_100_ original_order_currency
        decimal_64_30_ payment_amount
        varchar_64_ payment_currency
        datetime_3_ authorized_time
        decimal_64_30_ authorized_amount
        varchar_64_ authorized_currency
        decimal_64_30_ frozen_amount
        varchar_64_ frozen_currency
        decimal_64_30_ benefits_amount
        varchar_64_ benefits_currency
        decimal_64_30_ deduct_amount
        varchar_64_ deduct_currency
        decimal_64_30_ fee_amount
        varchar_64_ fee_currency
        decimal_64_30_ rebates_amount
        varchar_64_ rebates_currency
        datetime_3_ deduct_time
        varchar_100_ charging_scheme_code
        decimal_64_30_ base_fee_rate_pct
        decimal_64_30_ base_fee_amount
        varchar_100_ base_fee_currency
        decimal_64_30_ base_small_fixed_fee_amount
        varchar_100_ base_small_fixed_fee_currency
        decimal_64_30_ cross_border_fee_rate_pct
        decimal_64_30_ cross_border_fee_amount
        varchar_100_ cross_border_fee_currency
        decimal_64_30_ cross_border_small_fixed_fee_amount
        varchar_100_ cross_border_small_fixed_fee_currency
        decimal_64_30_ fx_fee_rate_pct
        decimal_64_30_ fx_fee_amount
        varchar_100_ fx_fee_currency
        decimal_64_30_ other_fee
        bigint bill_record_id
        varchar_255_ card_channel_bill_vendor_order_no
        varchar_255_ card_channel_bill_client_order_no
        bigint card_channel_bill_trade_time
        bigint card_channel_bill_trade_begin_time
        varchar_255_ card_channel_bill_fee
        varchar_255_ card_channel_bill_usdt_amount
        varchar_255_ card_channel_bill_reconciliation_currency
        tinyint card_channel_bill_status
        bigint card_channel_id
        varchar_100_ card_channel_code
        varchar_100_ card_channel_name
        varchar_64_ card_channel_zone_id
        decimal_64_30_ card_channel_capture_amount
        varchar_64_ card_channel_capture_currency
        varchar_64_ card_channel_capture_batch
        datetime_3_ card_channel_capture_time
        tinyint card_channel_authorized_status
        decimal_64_30_ card_channel_local_amount
        varchar_20_ card_channel_local_currency
        decimal_64_30_ card_channel_basic_service_rate
        decimal_64_30_ card_channel_basic_service_fee
        varchar_100_ card_channel_base_fee_currency
        decimal_64_30_ card_channel_cross_border_rate
        decimal_64_30_ card_channel_cross_border_fee
        decimal_64_30_ card_channel_cross_border_fixed_fee
        decimal_64_30_ card_channel_other_fees
        decimal_64_30_ card_channel_total_fee
        varchar_64_ card_channel_fee_currency
        decimal_64_30_ card_channel_frozen_amount
        varchar_64_ card_channel_frozen_currency
        decimal_64_30_ card_channel_deduct_amount
        varchar_64_ card_channel_deduct_currency
        bigint card_channel_authorized_time
        bigint card_channel_authorized_finish_time
        bigint card_channel_bill_id
        tinyint card_channel_bill_type
        varchar_64_ wallet_adjustment_trade_order_no
        decimal_64_30_ adjust_amount
        decimal_64_30_ adjust_amount_usd
        varchar_100_ adjust_currency
        varchar_50_ wallet_trade_order_no
        tinyint wallet_trade_direction
        varchar_100_ wallet_from_account_no
        varchar_100_ wallet_from_account_name
        tinyint wallet_from_account_type
        varchar_20_ wallet_from_currency_no
        varchar_20_ wallet_from_currency_code
        decimal_64_30_ wallet_from_amt
        varchar_100_ wallet_to_account_no
        varchar_100_ wallet_to_account_name
        tinyint wallet_to_account_type
        varchar_20_ wallet_to_currency_no
        varchar_20_ wallet_to_currency_code
        decimal_64_30_ wallet_to_amt
        decimal_64_30_ wallet_exchange_rate
        decimal_64_30_ wallet_fee_rate
        varchar_20_ wallet_fee_currency_no
        varchar_20_ wallet_fee_currency_code
        decimal_64_30_ wallet_fee_amt
        varchar_50_ benefits_trade_order_no
        tinyint benefits_trade_direction
        varchar_100_ benefits_from_account_no
        varchar_100_ benefits_from_account_name
        tinyint benefits_from_account_type
        varchar_20_ benefits_from_currency_no
        varchar_20_ benefits_from_currency_code
        decimal_64_30_ benefits_from_amt
        varchar_100_ benefits_to_account_no
        varchar_100_ benefits_to_account_name
        tinyint benefits_to_account_type
        varchar_20_ benefits_to_currency_no
        varchar_20_ benefits_to_currency_code
        decimal_64_30_ benefits_to_amt
        decimal_64_30_ benefits_exchange_rate
        decimal_64_30_ benefits_fee_rate
        varchar_20_ benefits_fee_currency_no
        varchar_20_ benefits_fee_currency_code
        decimal_64_30_ benefits_fee_amt
        varchar_50_ rebates_trade_order_no
        tinyint rebates_trade_direction
        varchar_100_ rebates_from_account_no
        varchar_100_ rebates_from_account_name
        tinyint rebates_from_account_type
        varchar_20_ rebates_from_currency_no
        varchar_20_ rebates_from_currency_code
        decimal_64_30_ rebates_from_amt
        varchar_100_ rebates_to_account_no
        varchar_100_ rebates_to_account_name
        tinyint rebates_to_account_type
        varchar_20_ rebates_to_currency_no
        varchar_20_ rebates_to_currency_code
        decimal_64_30_ rebates_to_amt
        decimal_64_30_ rebates_exchange_rate
        decimal_64_30_ rebates_fee_rate
        varchar_20_ rebates_fee_currency_no
        varchar_20_ rebates_fee_currency_code
        decimal_64_30_ rebates_fee_amt
        decimal_64_30_ flat_exchange_rate_gain_loss
        varchar_100_ flat_exchange_rate_gain_loss_currency
        decimal_64_30_ crypto_exchange_rate_gain_loss
        varchar_100_ crypto_exchange_rate_gain_loss_currency
        decimal_64_30_ crypto_hedge_profit_amount
        varchar_100_ crypto_hedge_profit_currency_currency
        decimal_64_30_ crypto_hedge_loss_amount
        varchar_100_ crypto_hedge_loss_currency_currency
        tinyint reconciliation_status
        tinyint reconciliation_result_type
        tinyint inner_reconciliation_result_type
        varchar_255_ remark
        varchar_64_ regulator
        datetime create_time
        datetime update_time
    }
    tb_card_purchase_quote_hit_record {
        int id
        varchar_255_ purchase_record_no
        varchar_100_ from_coin
        varchar_100_ from_coin_type
        varchar_100_ to_coin
        varchar_100_ to_coin_type
        decimal_64_30_ exchange_rate
        varchar_512_ quote_config_data
        varchar_4000_ quote_hit_data
        varchar_512_ missed_hit_reason
        datetime create_time
        varchar_255_ create_user
        datetime update_time
        varchar_255_ update_user
    }
    tb_card_purchase_record {
        bigint id
        varchar_64_ purchase_record_no
        varchar_64_ trade_order_no
        varchar_64_ channel_order_no
        varchar_64_ benefits_order_no
        varchar_64_ wallet_trade_order_no
        varchar_64_ wallet_convert_trade_order_no
        varchar_64_ wallet_adjustment_trade_order_no
        int user_id
        varchar_64_ wallet_account_no
        varchar_64_ card_account_no
        varchar_64_ card_id
        varchar_64_ card_no
        varchar_64_ channel_code
        decimal_64_30_ original_amount
        varchar_64_ original_currency
        decimal_64_30_ payment_amount
        varchar_64_ payment_currency
        decimal_64_30_ authorized_amount
        varchar_64_ authorized_currency
        datetime_3_ authorized_time
        tinyint authorized_status
        decimal_64_30_ capture_amount
        varchar_64_ capture_currency
        varchar_64_ capture_batch
        datetime_3_ capture_time
        decimal_64_30_ frozen_amount
        varchar_64_ frozen_currency
        decimal_64_30_ benefits_amount
        varchar_64_ benefits_currency
        decimal_64_30_ deduct_amount
        varchar_64_ deduct_currency
        datetime_3_ deduct_time
        decimal_64_30_ fee_amount
        varchar_64_ fee_currency
        decimal_64_30_ rate
        tinyint verify_3ds
        tinyint verify_3ds_type
        datetime_3_ verify_3ds_time
        decimal_64_30_ verify_3ds_usdt_amount
        tinyint verify_3ds_scene
        varchar_64_ merchant_name
        varchar_64_ authentication_id
        varchar_64_ transaction_id
        tinyint is_cross_border
        tinyint is_frictionless
        tinyint bill_type
        tinyint status
        datetime_3_ finish_time
        datetime_3_ wallet_fund_change_time
        varchar_255_ vcard_failed_code
        varchar_255_ channel_failed_code
        varchar_64_ fingerprint
        varchar_64_ regulator
        int version
        datetime_3_ create_time
        bigint create_user
        datetime_3_ update_time
        bigint update_user
    }
    tb_card_purchase_record_detail {
        bigint id
        varchar_64_ purchase_record_no
        varchar_64_ trade_order_no
        int user_id
        varchar_64_ mcc
        varchar_64_ consumption_category
        varchar_64_ merchant_name
        varchar_128_ merchant_address
        varchar_64_ charging_scheme_code
        decimal_64_30_ calculate_amount
        decimal_64_30_ basic_trx_rate
        decimal_64_30_ basic_trx_fee
        decimal_64_30_ basic_fixed_charge
        decimal_64_30_ cross_border_rate
        decimal_64_30_ cross_border_fee
        decimal_64_30_ cross_border_fixed_charge
        varchar_24_ cross_border_fixed_currency
        decimal_64_30_ fx_rate
        decimal_64_30_ fx_fee
        decimal_64_30_ other_fee
        decimal_64_30_ pre_check_amt
        varchar_24_ pre_check_currency
        decimal_64_30_ release_amount
        varchar_24_ release_currency
        datetime_3_ release_time
        decimal_64_30_ fiat_from_amount
        varchar_24_ fiat_from_currency
        decimal_64_30_ fiat_to_amount
        varchar_24_ fiat_to_currency
        varchar_24_ fiat_exchange_bp
        decimal_64_30_ fiat_exchange_rate
        decimal_64_30_ equivalent_amount
        varchar_24_ equivalent_currency
        decimal_64_30_ exchange_earnings
        varchar_24_ exchange_earnings_currency
        decimal_64_30_ wallet_convert_rate
        varchar_64_ regulator
        varchar_64_ fingerprint
        int version
        datetime_3_ create_time
    }
    tb_card_rebate_auto_claim_config {
        bigint id
        int user_id
        int status
        varchar_32_ regulator
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
    }
    tb_card_rebate_claim_order {
        bigint id
        varchar_64_ claim_order_no
        int user_id
        int claim_status
        decimal_64_30_ claim_amt
        varchar_20_ claim_currency_code
        varchar_64_ trade_order_no
        varchar_100_ claim_currency_account_no
        varchar_100_ wallet_currency_account_no
        bigint auto_config_id
        varchar_128_ note
        varchar_32_ regulator
        int version
        varchar_255_ fingerprint
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
    }
    tb_card_rebate_order {
        bigint id
        varchar_64_ rebates_order_no
        int user_id
        varchar_64_ card_trade_order_no
        int order_status
        int rebates_type
        decimal_64_30_ payment_amount
        varchar_10_ payment_currency
        varchar_64_ card_id
        varchar_64_ card_number
        decimal_64_30_ rebates_amt
        varchar_64_ campaign_id
        int user_vip_level
        decimal_64_30_ rebates_rate
        varchar_64_ trade_order_no
        varchar_64_ inner_trade_order_no
        varchar_64_ inner_account_id
        varchar_128_ note
        int upper_limit_reached
        datetime_3_ status_change_time
        varchar_32_ regulator
        varchar_255_ fingerprint
        int version
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
    }
    tb_card_refund_channel_order {
        bigint id
        bigint bill_id
        varchar_64_ channel_order_no
        varchar_64_ trade_order_no
        varchar_64_ refund_order_no
        varchar_64_ channel_purchase_order_no
        varchar_64_ channel_code
        int bill_type
        varchar_256_ merchant_name
        varchar_64_ card_currency
        decimal_64_30_ card_currency_amount
        decimal_64_30_ channel_order_amount
        varchar_64_ channel_order_currency
        decimal_64_30_ channel_service_rate
        decimal_64_30_ channel_service_fee
        varchar_64_ channel_fee_currency
        decimal_64_30_ channel_cross_border_rate
        decimal_64_30_ channel_cross_border_fee
        decimal_64_30_ channel_cross_border_fix_fee
        decimal_64_30_ channel_other_fees
        decimal_64_30_ channel_total_fees
        decimal_64_30_ channel_returned_amount
        varchar_64_ channel_returned_currency
        varchar_64_ channel_failed_code
        int channel_refund_status
        bigint create_timestamp
        bigint finish_timestamp
        bigint trade_begin_timestamp
        bigint trade_finish_timestamp
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
        varchar_12_ update_user
        int version
        varchar_64_ fingerprint
    }
    tb_card_refund_channel_reconciliation {
        bigint id
        varchar_64_ channel_code
        date reconciliation_date
        int reconciliation_count
        varchar_10_ reconciliation_currency
        decimal_64_30_ reconciliation_amount
        int channel_refund_order_count
        decimal_64_30_ channel_refund_order_amount
        varchar_10_ channel_refund_order_currency
        int vcard_refund_order_count
        decimal_64_30_ vcard_refund_order_amount
        varchar_10_ vcard_refund_order_currency
        decimal_64_30_ crypto_repair_price_difference_income_amount
        varchar_10_ crypto_repair_price_difference_income_currency
        decimal_64_30_ crypto_repair_price_difference_damaged_amount
        varchar_10_ crypto_repair_price_difference_damaged_currency
        int overpayment_order_count
        decimal_64_30_ overpayment_order_amount
        varchar_10_ overpayment_order_currency
        int shortage_order_count
        decimal_64_30_ shortage_order_amount
        varchar_10_ shortage_order_currency
        int channel_refund_fail_count
        decimal_64_30_ channel_refund_fail_amount_count
        int pending_reconciliation_order_count
        decimal_64_30_ pending_reconciliation_order_amount
        int daily_reconciliation_progress
        text daily_reconciliation_fail_desc
        tinyint cps_sync_status
        date trigger_reconciliation_time
        varchar_255_ remark
        datetime report_generation_time
        datetime create_time
        datetime update_time
    }
    tb_card_refund_channel_reconciliation_record {
        bigint id
        varchar_100_ reconciliation_record_no
        date reconciliation_date
        varchar_100_ trade_order_no
        varchar_100_ refund_order_no
        varchar_100_ purchase_record_no
        varchar_64_ benefit_order_no
        varchar_64_ deduct_order_no
        bigint business_record_time
        int refund_status
        int refund_type
        varchar_64_ channel_code
        varchar_64_ card_channel_zone_id
        int charging_scheme_id
        varchar_64_ card_id
        varchar_64_ card_no
        varchar_64_ wallet_account_no
        int user_id
        varchar_64_ user_merchant_id
        varchar_255_ user_merchant_code
        decimal_64_30_ refund_amount
        varchar_64_ refund_currency
        decimal_64_30_ refund_rate
        decimal_64_30_ refund_fee
        decimal_64_30_ fixed_fee
        decimal_64_30_ other_fees
        decimal_64_30_ total_fee
        decimal_64_30_ exchange_rate_difference
        varchar_64_ fee_currency
        decimal_64_30_ benefit_pay_amount
        varchar_64_ card_currency
        decimal_64_30_ deduct_amount
        decimal_64_30_ reward_amount
        decimal_64_30_ original_trade_fee
        decimal_64_30_ original_trade_channel_fee
        decimal_64_30_ returned_fee
        decimal_64_30_ returned_amount
        varchar_64_ returned_currency
        datetime_3_ returned_time
        bigint create_timestamp
        bigint finish_timestamp
        int order_source
        decimal_64_30_ card_channel_purchase_local_amount
        varchar_20_ card_channel_purchase_local_currency
        decimal_64_30_ card_channel_purchase_basic_service_rate
        decimal_64_30_ card_channel_purchase_basic_service_fee
        varchar_100_ card_channel_purchase_base_fee_currency
        decimal_64_30_ card_channel_purchase_cross_border_rate
        decimal_64_30_ card_channel_purchase_cross_border_fee
        decimal_64_30_ card_channel_purchase_cross_border_fixed_fee
        decimal_64_30_ card_channel_purchase_other_fees
        decimal_64_30_ card_channel_purchase_total_fee
        varchar_64_ card_channel_purchase_fee_currency
        decimal_64_30_ card_channel_purchase_frozen_amount
        varchar_64_ card_channel_purchase_frozen_currency
        decimal_64_30_ card_channel_purchase_deduct_amount
        varchar_64_ card_channel_purchase_deduct_currency
        decimal_64_30_ card_channel_purchase_refund_amount_count
        bigint bill_record_id
        varchar_255_ card_channel_bill_vendor_order_no
        varchar_255_ card_channel_bill_client_order_no
        bigint card_channel_bill_trade_time
        bigint card_channel_bill_trade_begin_time
        varchar_255_ card_channel_bill_fee
        varchar_255_ card_channel_bill_usdt_amount
        varchar_255_ card_channel_bill_reconciliation_currency
        tinyint card_channel_bill_status
        varchar_64_ card_channel_order_no
        decimal_64_30_ card_channel_currency_amount
        decimal_64_30_ card_channel_order_amount
        varchar_64_ card_channel_order_currency
        decimal_64_30_ card_channel_service_rate
        decimal_64_30_ card_channel_service_fee
        varchar_64_ card_channel_fee_currency
        decimal_64_30_ card_channel_cross_border_rate
        decimal_64_30_ card_channel_cross_border_fee
        decimal_64_30_ card_channel_cross_border_fix_fee
        decimal_64_30_ card_channel_other_fees
        decimal_64_30_ card_channel_total_fees
        decimal_64_30_ card_channel_returned_amount
        varchar_64_ card_channel_returned_currency
        bigint card_channel_returned_time
        bigint card_channel_notify_time
        datetime_3_ card_channel_process_time
        datetime_3_ card_channel_update_time
        bigint card_channel_bill_id
        tinyint card_channel_bill_type
        bigint card_channel_trade_time
        bigint card_channel_trade_begin_time
        varchar_64_ wallet_adjustment_trade_order_no
        decimal_64_30_ adjust_amount_usd
        decimal_64_30_ adjust_amount
        varchar_100_ adjust_currency
        varchar_50_ wallet_trade_order_no
        tinyint wallet_trade_direction
        varchar_100_ wallet_from_account_no
        varchar_100_ wallet_from_account_name
        tinyint wallet_from_account_type
        varchar_20_ wallet_from_currency_no
        varchar_20_ wallet_from_currency_code
        decimal_64_30_ wallet_from_amt
        varchar_100_ wallet_to_account_no
        varchar_100_ wallet_to_account_name
        tinyint wallet_to_account_type
        varchar_20_ wallet_to_currency_no
        varchar_20_ wallet_to_currency_code
        decimal_64_30_ wallet_to_amt
        decimal_64_30_ wallet_exchange_rate
        decimal_64_30_ wallet_fee_rate
        varchar_20_ wallet_fee_currency_no
        varchar_20_ wallet_fee_currency_code
        decimal_64_30_ wallet_fee_amt
        varchar_50_ benefits_trade_order_no
        tinyint benefits_trade_direction
        varchar_100_ benefits_from_account_no
        varchar_100_ benefits_from_account_name
        tinyint benefits_from_account_type
        varchar_20_ benefits_from_currency_no
        varchar_20_ benefits_from_currency_code
        decimal_64_30_ benefits_from_amt
        varchar_100_ benefits_to_account_no
        varchar_100_ benefits_to_account_name
        tinyint benefits_to_account_type
        varchar_20_ benefits_to_currency_no
        varchar_20_ benefits_to_currency_code
        decimal_64_30_ benefits_to_amt
        decimal_64_30_ benefits_exchange_rate
        decimal_64_30_ benefits_fee_rate
        varchar_20_ benefits_fee_currency_no
        varchar_20_ benefits_fee_currency_code
        decimal_64_30_ benefits_fee_amt
        varchar_50_ rebates_trade_order_no
        tinyint rebates_trade_direction
        varchar_100_ rebates_from_account_no
        varchar_100_ rebates_from_account_name
        tinyint rebates_from_account_type
        varchar_20_ rebates_from_currency_no
        varchar_20_ rebates_from_currency_code
        decimal_64_30_ rebates_from_amt
        varchar_100_ rebates_to_account_no
        varchar_100_ rebates_to_account_name
        tinyint rebates_to_account_type
        varchar_20_ rebates_to_currency_no
        varchar_20_ rebates_to_currency_code
        decimal_64_30_ rebates_to_amt
        decimal_64_30_ rebates_exchange_rate
        decimal_64_30_ rebates_fee_rate
        varchar_20_ rebates_fee_currency_no
        varchar_20_ rebates_fee_currency_code
        decimal_64_30_ rebates_fee_amt
        decimal_64_30_ crypto_repair_price_difference_income
        varchar_100_ crypto_repair_price_difference_income_currency
        decimal_64_30_ crypto_repair_price_difference_damaged
        varchar_100_ crypto_repair_price_difference_damaged_currency
        tinyint reconciliation_status
        tinyint reconciliation_result_type
        tinyint inner_reconciliation_result_type
        varchar_255_ remark
        varchar_64_ regulator
        datetime create_time
        datetime update_time
        decimal_64_30_ purchase_deduct_amount
        varchar_64_ purchase_deduct_currency
        decimal_64_30_ purchase_fee_amount
        varchar_64_ purchase_fee_currency
    }
    tb_card_refund_record {
        bigint id
        varchar_64_ refund_order_no
        varchar_64_ trade_order_no
        varchar_64_ purchase_order_no
        varchar_64_ channel_refund_order_no
        varchar_64_ benefit_order_no
        varchar_64_ deduct_order_no
        varchar_64_ wallet_adjustment_trade_order_no
        varchar_64_ channel_code
        int charging_scheme_id
        varchar_64_ card_id
        varchar_64_ card_no
        varchar_64_ wallet_account_no
        int user_id
        varchar_64_ regulator
        int refund_type
        decimal_64_30_ refund_amount
        varchar_64_ refund_currency
        decimal_64_30_ refund_rate
        decimal_64_30_ refund_fee
        decimal_64_30_ fixed_fee
        decimal_64_30_ other_fees
        decimal_64_30_ total_fee
        decimal_64_30_ exchange_rate_difference
        varchar_64_ fee_currency
        varchar_64_ card_currency
        decimal_64_30_ deduct_amount
        decimal_64_30_ reward_amount
        decimal_64_30_ original_trade_fee
        decimal_64_30_ channel_trade_fee
        decimal_64_30_ returned_fee
        decimal_64_30_ returned_amount
        varchar_64_ returned_currency
        datetime_3_ returned_time
        varchar_512_ notes
        varchar_512_ review_comment
        int refund_status
        varchar_64_ vcard_failed_code
        varchar_64_ channel_failed_code
        bigint create_timestamp
        bigint finish_timestamp
        datetime_3_ create_time
        datetime_3_ update_time
        bigint trade_begin_timestamp
        bigint trade_finish_timestamp
        varchar_12_ create_user
        varchar_12_ update_user
        int order_source
        int version
        varchar_64_ fingerprint
    }
    tb_card_refund_record_audit {
        bigint id
        varchar_64_ task_no
        varchar_64_ refund_order_no
        varchar_12_ operative
        varchar_512_ notes
        int audit_result
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
        varchar_12_ update_user
        int version
        varchar_64_ fingerprint
    }
    tb_card_risk_accredit_record {
        int id
        varchar_50_ accredit_record_no
        varchar_50_ purchase_record_no
        tinyint type
        tinyint status
        varchar_50_ result_code
        json error_data
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
        int version
    }
    tb_card_risk_auth_record {
        int id
        varchar_50_ auth_record_no
        varchar_50_ purchase_record_no
        tinyint client_type
        varchar_50_ three_ds_order_no
        tinyint status
        varchar_50_ result_code
        json error_data
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
        int version
    }
    tb_card_risk_country {
        bigint id
        varchar_255_ display_name
        varchar_255_ cn_name
        varchar_50_ code_two
        varchar_50_ code_three
        datetime_3_ create_time
        varchar_50_ level
    }
    tb_card_risk_factor {
        bigint id
        varchar_64_ factor_group_id
        varchar_64_ user_id
        varchar_64_ order_id
        varchar_32_ verification_stage
        varchar_32_ factor_code
        varchar_64_ factor_name
        varchar_16_ factor_level_risk
        datetime create_time
    }
    tb_card_risk_factor_record {
        int id
        varchar_50_ factor_code
        text parameter
        varchar_50_ result_code
        tinyint type
        varchar_50_ ref_record_no
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
        int version
    }
    tb_card_risk_group {
        int id
        varchar_50_ group_no
        tinyint group_code
        tinyint group_type
        int group_strategy
        tinyint verify_method
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
        int version
    }
    tb_card_risk_mcc {
        int id
        bigint mcc_code
        varchar_1024_ title
        varchar_500_ cn_name
        varchar_50_ level
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
        int version
    }
    tb_card_risk_rule {
        int id
        varchar_50_ rule_no
        varchar_50_ rule_code
        tinyint rule_type
        int rule_version
        varchar_50_ risk_factor_value
        tinyint group_code
        tinyint is_deleted
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
        int version
    }
    tb_card_three_ds {
        bigint id
        varchar_64_ three_ds_order_no
        varchar_64_ auth_record_no
        varchar_64_ purchase_record_no
        int auth_form
        varchar_64_ temp_token
        varchar_64_ session_id
        int user_id
        varchar_64_ card_id
        int auth_type
        int verify_method
        int notify_type
        varchar_64_ device_id
        varchar_64_ ip_address
        varchar_64_ regulator
        varchar_8_ otp_code
        datetime_3_ notice_send_time
        tinyint_1_ notice_send_ack
        int status
        varchar_1024_ auth_result
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
        varchar_12_ update_user
        datetime_3_ expire_time
        int version
        varchar_64_ fingerprint
    }
    tb_card_trade_card_risk {
        bigint id
        varchar_64_ order_id
        varchar_64_ user_id
        varchar_32_ exception_code
        varchar_255_ exception_desc
        datetime create_time
    }
    tb_card_trade_flow {
        bigint id
        varchar_64_ trade_flow_no
        varchar_64_ trade_order_no
        varchar_64_ card_no
        varchar_64_ wallet_account_no
        varchar_64_ wallet_currency_account_no
        varchar_64_ currency_code
        decimal_64_30_ trade_amount
        decimal_64_30_ fee_amount
        decimal_64_30_ pay_amount
        decimal_64_30_ usdt_pay_amount
        varchar_64_ benefits_currency
        decimal_64_30_ benefit_amount
        decimal_64_30_ rebates_amount
        varchar_64_ rebates_currency
        decimal_64_30_ available_amount
        tinyint payment_type
        varchar_64_ from_account_no
        varchar_255_ from_account_currency
        varchar_64_ to_account_no
        varchar_255_ to_account_currency
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
        varchar_12_ update_user
        int version
        varchar_64_ fingerprint
    }
    tb_card_trade_order {
        bigint id
        varchar_64_ trade_order_no
        varchar_64_ wallet_trade_order_no
        varchar_64_ external_order_no
        varchar_64_ card_account_no
        varchar_64_ wallet_account_no
        varchar_64_ wallet_currency_account_no
        int user_id
        varchar_64_ channel_code
        int charging_scheme_id
        varchar_64_ cardholder_id
        varchar_64_ card_id
        varchar_64_ card_no
        datetime_3_ trade_time
        datetime_3_ audit_time
        datetime_3_ finish_time
        tinyint payment_type
        int refund_type
        decimal_64_30_ trade_amount
        decimal_64_30_ pay_amount
        varchar_64_ currency_code
        decimal_64_30_ usdt_pay_amount
        decimal_64_30_ fee_amount
        decimal_64_30_ fee_rate
        decimal_64_30_ exchange_rate
        decimal_64_30_ calculate_exchange_rate
        datetime_3_ wallet_fund_change_time
        varchar_64_ benefits_currency
        decimal_64_30_ benefits_amount
        decimal_64_30_ rebates_amount
        varchar_64_ rebates_currency
        varchar_255_ merchant_name
        varchar_255_ merchant_addr
        varchar_20_ consumption_categories
        int status
        int version
        varchar_64_ fingerprint
        varchar_64_ regulator
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_12_ create_user
        varchar_12_ update_user
    }
    tb_card_trade_order_charging_scheme {
        bigint id
        varchar_64_ trade_order_no
        varchar_64_ scheme_code
        int scheme_version
        text calculate_parameter
        varchar_255_ fingerprint
        varchar_255_ create_user
        datetime create_time
        varchar_255_ update_user
        datetime update_time
    }
    tb_card_upay_asset_flow_record {
        bigint id
        bigint asset_flow_id
        int card_pool_id
        int vendor_card_id
        varchar_255_ vendor_order_no
        varchar_255_ client_order_no
        int op_type
        varchar_255_ amount
        int item_id
        int direction
        bigint channel_create_time
        int push
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    tb_card_upay_bill_record {
        bigint id
        bigint bill_id
        int vendor_id
        int vendor_card_id
        int third_channel_id
        varchar_255_ user_id
        int card_pool_id
        varchar_255_ vendor_business_card_id
        varchar_255_ vendor_order_no
        varchar_255_ client_order_no
        int bill_type
        varchar_64_ vendor_bill_type
        varchar_255_ currency_amount
        int currency_id
        int tx_item_id
        varchar_255_ tx_amount
        varchar_255_ fee
        varchar_255_ usdt_amount
        int status
        int direction
        varchar_255_ trade_merchant
        bigint trade_time
        bigint trade_begin_time
        int push
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    tb_card_upay_chain_asset_record {
        bigint id
        bigint uce_id
        int type
        int item_id
        varchar_255_ tx_id
        varchar_100_ chain_tag
        varchar_100_ num
        varchar_100_ status
        varchar_100_ network_fee
        bigint channel_create_time
        int push
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    tb_card_upay_projection_account {
        bigint id
        varchar_100_ projection_account_no
        varchar_100_ currency_type
        varchar_100_ currency
        decimal_64_30_ end_day_account_balance
        decimal_64_30_ end_day_frozen_balance
        decimal_64_30_ end_day_available_balance
        decimal_64_30_ today_deposit
        decimal_64_30_ today_withdrawal
        decimal_64_30_ account_balance
        decimal_64_30_ frozen_balance
        decimal_64_30_ available_balance
        varchar_255_ data_fingerprint
        int version
        datetime update_cst_time
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    tb_card_upay_projection_account_record {
        bigint id
        varchar_100_ projection_account_no
        int fund_movement_direction
        int transaction_attribution
        int transaction_type
        varchar_255_ channel_order_id
        varchar_255_ channel_record_id
        varchar_255_ card_bill_id
        varchar_255_ card_order_id
        int business_type
        decimal_64_30_ occur_total_amount
        decimal_64_30_ occur_order_amount
        decimal_64_30_ occur_fee_amount
        decimal_64_30_ begin_account_balance
        decimal_64_30_ begin_frozen_balance
        decimal_64_30_ begin_available_balance
        decimal_64_30_ end_account_balance
        decimal_64_30_ end_frozen_balance
        decimal_64_30_ end_available_balance
        decimal_64_30_ deposit_cumulative_amount
        decimal_64_30_ withdrawal_cumulative_amount
        varchar_100_ currency
        varchar_100_ user_id
        bigint channel_timestamp
        datetime channel_time
        bigint channel_create_timestamp
        datetime channel_create_time
        varchar_255_ data_fingerprint
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    tb_card_upay_projection_daily_statistics {
        bigint id
        varchar_100_ currency
        decimal_64_30_ start_balance
        decimal_64_30_ deposit_amount
        decimal_64_30_ withdrawal_amount
        decimal_64_30_ deduction_amount
        decimal_64_30_ end_day_account_balance
        decimal_64_30_ end_day_frozen_balance
        decimal_64_30_ end_day_available_balance
        decimal_64_30_ end_day_security_amount
        int card_activation_count
        decimal_64_30_ card_activation_amount
        int card_activation_failed_count
        decimal_64_30_ card_activation_return_amount
        int card_cancellation_count
        decimal_64_30_ card_cancellation_amount
        int card_consumption_total_authorization_count
        decimal_64_30_ card_consumption_total_authorization_amount
        decimal_64_30_ card_consumption_total_authorization_fee
        int card_consumption_authorization_count
        decimal_64_30_ card_consumption_authorization_amount
        decimal_64_30_ card_consumption_fee_amount
        int card_order_cancel_count
        decimal_64_30_ card_order_cancel_amount
        decimal_64_30_ card_order_cancel_fee_amount
        int card_refund_count
        decimal_64_30_ card_refund_amount
        decimal_64_30_ card_refund_fee_amount
        int card_consumption_settlement_adjustment_count
        decimal_64_30_ card_consumption_settlement_adjustment_amount
        decimal_64_30_ card_consumption_settlement_adjustment_fee_amount
        int card_refund_settlement_adjustment_count
        decimal_64_30_ card_refund_settlement_adjustment_amount
        decimal_64_30_ card_refund_settlement_adjustment_fee_amount
        int card_withdrawal_count
        decimal_64_30_ card_withdrawal_amount
        decimal_64_30_ card_withdrawal_fee_amount
        decimal_64_30_ total_transaction_fee
        int settlement_count
        decimal_64_30_ settlement_amount
        datetime statistics_date
        varchar_255_ data_fingerprint
        datetime create_time
        varchar_100_ create_user
    }
    tb_card_upgrade_record {
        bigint id
        varchar_64_ upgrade_record_no
        varchar_64_ card_id
        varchar_64_ card_holder_id
        int user_id
        int user_vip_level
        tinyint src_card_level
        tinyint des_card_level
        tinyint upgrade_status
        int version
        int retry_count
        tinyint is_deleted
        varchar_255_ create_user
        datetime create_time
        varchar_255_ update_user
        datetime update_time
    }
    tb_card_user_city {
        bigint id
        varchar_64_ user_id
        varchar_64_ ip
        varchar_32_ country_code
        varchar_64_ city
    }
    tb_card_user_setting {
        bigint id
        varchar_64_ user_id
        varchar_128_ device_id
        tinyint_1_ password_free_on
        tinyint_1_ face_id_on
        tinyint_1_ touch_id_on
        tinyint is_deleted
        datetime create_time
        datetime update_time
        varchar_64_ create_user
    }
    tb_card_vip_recommend {
        bigint id
        varchar_64_ user_id
        varchar_64_ cardholder_id
        varchar_64_ wallet_account_no
        varchar_64_ user_name
        varchar_64_ recommend_code
        varchar_64_ tel_no
        varchar_64_ user_email
        varchar_64_ country
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
        varchar_64_ fingerprint
        varchar_255_ wallet_account_status
        tinyint is_delete
        varchar_255_ batch_num
        datetime_3_ recommend_code_expire_time
        varchar_255_ input_contry
        datetime_3_ add_recommend_code_time
        datetime_3_ bind_recommend_code_time
        tinyint recommend_code_status
        varchar_255_ input_user_name
        tinyint whether_synchronized
        tinyint whether_effective_user
    }
    tb_card_vip_recommend_copy1 {
        bigint id
        varchar_64_ user_id
        varchar_64_ cardholder_id
        varchar_64_ wallet_account_no
        varchar_64_ user_name
        varchar_64_ recommend_code
        varchar_64_ tel_no
        varchar_64_ user_email
        varchar_64_ country
        datetime_3_ create_time
        datetime_3_ update_time
        varchar_64_ create_user
        varchar_64_ update_user
        varchar_64_ fingerprint
        varchar_255_ wallet_account_status
        tinyint is_delete
        varchar_255_ batch_num
        datetime_3_ recommend_code_expire_time
        varchar_255_ input_contry
        datetime_3_ add_recommend_code_time
        datetime_3_ bind_recommend_code_time
        tinyint recommend_code_status
        varchar_255_ input_user_name
        tinyint whether_synchronized
        tinyint whether_effective_user
    }
    tb_card_charging_scheme ||--o{ tb_card_trade_order : "has"
    tb_card_upay_bill_record ||--o{ tb_card_purchase_channel_reconciliation_record : "has"
    tb_card_channel ||--o{ tb_card_purchase_channel_reconciliation_record : "has"
    tb_card_risk_country ||--o{ tb_card_customer_whitelist : "has"
    tb_card_payment_limit ||--o{ tb_card_payment_limit_country_map : "has"
    tb_card_risk_country ||--o{ tb_card_payment_limit_country_map : "has"
    tb_card_risk_country ||--o{ tb_card_kyc_info_history : "has"
    tb_card_charging_scheme ||--o{ tb_card_refund_channel_reconciliation_record : "has"
    tb_card_upay_bill_record ||--o{ tb_card_refund_channel_reconciliation_record : "has"
    tb_card_upay_asset_flow_record ||--o{ tb_card_apply_channel_reconciliation_record : "has"
    tb_card_trade_order ||--o{ tb_card_trade_card_risk : "has"
    tb_card_payment_limit ||--o{ tb_card_payment_limit_card_map : "has"
    tb_card_refund_channel_order ||--o{ tb_card_upay_projection_account_record : "has"
    tb_card_risk_country ||--o{ tb_card_country_whitelist : "has"
    tb_card_trade_order ||--o{ tb_card_risk_factor : "has"
    tb_card_upay_bill_record ||--o{ tb_card_purchase_channel_pending_recon_snap : "has"
    tb_card_channel ||--o{ tb_card_purchase_channel_pending_recon_snap : "has"
    tb_card_risk_country ||--o{ tb_card_channel_country_blacklist : "has"
    tb_card_risk_country ||--o{ tb_card_info : "has"
    tb_card_charging_scheme ||--o{ tb_card_refund_record : "has"

    %% Cross-category references:
    %% tb_marketing_dashboard_user (external) --> tb_card_apply_channel_audit
    %% tb_marketing_dashboard_user (external) --> tb_card_trade_order
    %% tb_marketing_dashboard_user (external) --> tb_card_purchase_channel_reconciliation_record
    %% tb_marketing_dashboard_user (external) --> tb_card_account
    %% tb_marketing_dashboard_user (external) --> tb_card_customer_whitelist
    %% tb_country (external) --> tb_card_customer_whitelist
    %% tb_exchange_rate_limit (external) --> tb_card_payment_limit_country_map
    %% tb_country (external) --> tb_card_payment_limit_country_map
    %% tb_marketing_dashboard_user (external) --> tb_card_user_city
    %% tb_marketing_dashboard_user (external) --> tb_card_message_notify
    %% tb_marketing_dashboard_user (external) --> tb_card_kyc_info_history
    %% tb_country (external) --> tb_card_kyc_info_history
    %% tb_marketing_dashboard_user (external) --> tb_card_apply_record
    %% tb_marketing_dashboard_user (external) --> tb_card_purchase_channel_order
    %% tb_marketing_dashboard_user (external) --> tb_card_refund_channel_reconciliation_record
    %% tb_marketing_dashboard_user (external) --> tb_card_vip_recommend
    %% tb_marketing_dashboard_user (external) --> tb_card_user_setting
    %% tb_marketing_dashboard_user (external) --> tb_card_apply_channel_reconciliation_record
    %% tb_marketing_dashboard_user (external) --> tb_card_bin_record
    %% tb_marketing_dashboard_user (external) --> tb_card_purchase_record
    %% tb_user_coupon_trade_record_transaction (external) --> tb_card_purchase_record
    %% tb_marketing_dashboard_user (external) --> tb_card_upgrade_record
    %% old_tb_wallet_ingress_withdraw_order (external) --> tb_card_trade_card_risk
    %% tb_marketing_dashboard_user (external) --> tb_card_trade_card_risk
    %% tb_marketing_dashboard_user (external) --> tb_card_purchase_record_detail
    %% tb_exchange_rate_limit (external) --> tb_card_payment_limit_card_map
    %% tb_marketing_dashboard_user (external) --> tb_card_rebate_claim_order
    %% tb_marketing_dashboard_user (external) --> tb_card_upay_projection_account_record
    %% tb_marketing_dashboard_user (external) --> tb_card_operation_record
    %% tb_country (external) --> tb_card_country_whitelist
    %% tb_salary_rule_factor_group (external) --> tb_card_risk_factor
    %% tb_marketing_dashboard_user (external) --> tb_card_risk_factor
    %% old_tb_wallet_ingress_withdraw_order (external) --> tb_card_risk_factor
    %% tb_marketing_dashboard_user (external) --> tb_card_rebate_auto_claim_config
    %% tb_pt_session (external) --> tb_card_three_ds
    %% tb_marketing_dashboard_user (external) --> tb_card_three_ds
    %% tb_marketing_dashboard_user (external) --> tb_card_vip_recommend_copy1
    %% tb_marketing_dashboard_user (external) --> tb_card_black_list
    %% tb_marketing_dashboard_user (external) --> tb_card_upay_bill_record
    %% tb_commission_package_group_currency (external) --> tb_card_upay_bill_record
    %% tb_marketing_dashboard_user (external) --> tb_card_purchase_channel_pending_recon_snap
    %% tb_country (external) --> tb_card_channel_country_blacklist
    %% tb_marketing_dashboard_user (external) --> tb_card_customer_info
    %% tb_marketing_dashboard_user (external) --> tb_card_info
    %% tb_country (external) --> tb_card_info
    %% tb_business_file (external) --> tb_card_file_upload_record
    %% tb_marketing_dashboard_user (external) --> tb_card_rebate_order
    %% tb_marketing_dashboard_user (external) --> tb_card_refund_record