%% Category: regulator (1 tables)
erDiagram
    tb_regulator_group_rule {
        bigint id
        varchar_30_ regulator
        varchar_30_ group_rule
        varchar_200_ process_note
        varchar_50_ operator
        tinyint_1_ is_del
        datetime create_time
    }