%% Category: mq (1 tables)
erDiagram
    tb_mq_send_log {
        bigint_unsigned id
        int user_id
        varchar_10_ regulator
        varchar_64_ business_type
        varchar_64_ src_app_id
        varchar_128_ business_order_no
        varchar_4096_ send_msg
        tinyint_1_ is_del
        datetime create_time
        datetime update_time
    }

    %% Cross-category references:
    %% tb_marketing_dashboard_user (external) --> tb_mq_send_log