%% Category: doris (1 tables)
erDiagram
    tb_doris_catalog_task_retry {
        int id
        int regulate
        varchar_32_ table_name
        date calculation_time
        varchar_1024_ doris_sql
        tinyint status
        int retry_number
        datetime create_time
        datetime update_time
        tinyint is_del
    }