%% Category: alpha (1 tables)
erDiagram
    tb_alpha_config {
        int id
        varchar_255_ alpha_name
        varchar_200_ key
        varchar_200_ config
        datetime create_time
        datetime update_time
        tinyint_1_ is_del
    }