%% Category: batch (1 tables)
erDiagram
    tb_batch_ib_commission_operation_log {
        int id
        varchar_50_ server
        int ib_user_id
        varchar_255_ ib_user_name
        varchar_255_ old_sales
        varchar_255_ new_sales
        int status
        varchar_255_ noted
        varchar_255_ type
        varchar_255_ commission_change
        int operation_id
        int mission_type
    }