%% Category: city (1 tables)
erDiagram
    tb_city {
        int CityID
        varchar_50_ CityName
        varchar_50_ ZipCode
        int ProvinceID
        datetime DateCreated
        datetime DateUpdated
        varchar_50_ cityCode
        tinyint is_del
        varchar_50_ operator
    }