%% Category: data (13 tables)
erDiagram
    tb_data_cleaning_record {
        bigint id
        varchar_128_ cleaning_task_name
        varchar_255_ cleaning_task_code
        datetime execution_time
        tinyint_1_ execution_status
        bigint cleaned_count
        varchar_1024_ error_msg
        int cleaning_duration
        bigint create_user
        datetime create_time
        bigint update_user
        datetime update_time
        tinyint_1_ is_del
    }
    tb_data_source {
        int id
        varchar_20_ datasource_key
        varchar_20_ datasource_meta
        int business_id
        varchar_100_ data_name
        varchar_100_ data_ip
        varchar_100_ data_user
        varchar_100_ data_pass
        int status
        int is_del
        varchar_10_ database_type
        int source_web_side_type
        varchar_100_ comment
        int mt4_user
        varchar_100_ mt4_pass
        varchar_100_ data_base_name
        varchar_100_ mt4_live_ip
        varchar_100_ mt4_demo_ip
        int database_port
        varchar_255_ loginDesign
        varchar_10_ regulator
        int parent_id
        tinyint_1_ is_slave_db
        datetime create_time
        datetime update_time
        varchar_100_ operator
        varchar_250_ db_proxy_ip
    }
    tb_data_source_225-8-19 {
        int id
        varchar_20_ datasource_key
        varchar_20_ datasource_meta
        int business_id
        varchar_100_ data_name
        varchar_100_ data_ip
        varchar_100_ data_user
        varchar_100_ data_pass
        int status
        int is_del
        varchar_10_ database_type
        int source_web_side_type
        varchar_100_ comment
        int mt4_user
        varchar_100_ mt4_pass
        varchar_100_ data_base_name
        varchar_100_ mt4_live_ip
        varchar_100_ mt4_demo_ip
        int database_port
        varchar_255_ loginDesign
        varchar_10_ regulator
        int parent_id
        tinyint_1_ is_slave_db
        datetime create_time
        datetime update_time
        varchar_100_ operator
    }
    tb_data_source_backup250907 {
        int id
        varchar_20_ datasource_key
        varchar_20_ datasource_meta
        int business_id
        varchar_100_ data_name
        varchar_100_ data_ip
        varchar_100_ data_user
        varchar_100_ data_pass
        int status
        int is_del
        varchar_10_ database_type
        int source_web_side_type
        varchar_100_ comment
        int mt4_user
        varchar_100_ mt4_pass
        varchar_100_ data_base_name
        varchar_100_ mt4_live_ip
        varchar_100_ mt4_demo_ip
        int database_port
        varchar_255_ loginDesign
        varchar_10_ regulator
        int parent_id
        tinyint_1_ is_slave_db
        datetime create_time
        datetime update_time
        varchar_100_ operator
    }
    tb_data_source_backup260518 {
        int id
        varchar_20_ datasource_key
        varchar_20_ datasource_meta
        int business_id
        varchar_100_ data_name
        varchar_100_ data_ip
        varchar_100_ data_user
        varchar_100_ data_pass
        int status
        int is_del
        varchar_10_ database_type
        int source_web_side_type
        varchar_100_ comment
        int mt4_user
        varchar_100_ mt4_pass
        varchar_100_ data_base_name
        varchar_100_ mt4_live_ip
        varchar_100_ mt4_demo_ip
        int database_port
        varchar_255_ loginDesign
        varchar_10_ regulator
        int parent_id
        tinyint_1_ is_slave_db
        datetime create_time
        datetime update_time
        varchar_100_ operator
        varchar_250_ db_proxy_ip
    }
    tb_data_source_dbtest {
        int id
        varchar_20_ datasource_key
        varchar_20_ datasource_meta
        int business_id
        varchar_100_ data_name
        varchar_100_ data_ip
        varchar_100_ data_user
        varchar_100_ data_pass
        int status
        int is_del
        varchar_10_ database_type
        int source_web_side_type
        varchar_100_ comment
        int mt4_user
        varchar_100_ mt4_pass
        varchar_100_ data_base_name
        varchar_100_ mt4_live_ip
        varchar_100_ mt4_demo_ip
        int database_port
        varchar_255_ loginDesign
        varchar_10_ regulator
        int parent_id
        tinyint_1_ is_slave_db
        varchar_10_ privilege
        varchar_10_ region
        varchar_20_ db_classify
        datetime create_time
        datetime update_time
        varchar_100_ operator
    }
    tb_data_source_hk_r {
        int id
        varchar_20_ datasource_key
        varchar_20_ datasource_meta
        int business_id
        varchar_100_ data_name
        varchar_100_ data_ip
        varchar_100_ data_user
        varchar_100_ data_pass
        int status
        int is_del
        varchar_10_ database_type
        int source_web_side_type
        varchar_100_ comment
        int mt4_user
        varchar_100_ mt4_pass
        varchar_100_ data_base_name
        varchar_100_ mt4_live_ip
        varchar_100_ mt4_demo_ip
        int database_port
        varchar_255_ loginDesign
        varchar_10_ regulator
        int parent_id
        tinyint_1_ is_slave_db
        datetime create_time
        datetime update_time
        varchar_100_ operator
    }
    tb_data_source_mena_r {
        int id
        varchar_20_ datasource_key
        varchar_20_ datasource_meta
        int business_id
        varchar_100_ data_name
        varchar_100_ data_ip
        varchar_100_ data_user
        varchar_100_ data_pass
        int status
        int is_del
        varchar_10_ database_type
        int source_web_side_type
        varchar_100_ comment
        int mt4_user
        varchar_100_ mt4_pass
        varchar_100_ data_base_name
        varchar_100_ mt4_live_ip
        varchar_100_ mt4_demo_ip
        int database_port
        varchar_255_ loginDesign
        varchar_10_ regulator
        int parent_id
        tinyint_1_ is_slave_db
        datetime create_time
        datetime update_time
        varchar_100_ operator
    }
    tb_data_source_nv_r {
        int id
        varchar_20_ datasource_key
        varchar_20_ datasource_meta
        int business_id
        varchar_100_ data_name
        varchar_100_ data_ip
        varchar_100_ data_user
        varchar_100_ data_pass
        int status
        int is_del
        varchar_10_ database_type
        int source_web_side_type
        varchar_100_ comment
        int mt4_user
        varchar_100_ mt4_pass
        varchar_100_ data_base_name
        varchar_100_ mt4_live_ip
        varchar_100_ mt4_demo_ip
        int database_port
        varchar_255_ loginDesign
        varchar_10_ regulator
        int parent_id
        tinyint_1_ is_slave_db
        datetime create_time
        datetime update_time
        varchar_100_ operator
    }
    tb_data_source_nv_rw {
        int id
        varchar_20_ datasource_key
        varchar_20_ datasource_meta
        int business_id
        varchar_100_ data_name
        varchar_100_ data_ip
        varchar_100_ data_user
        varchar_100_ data_pass
        int status
        int is_del
        varchar_10_ database_type
        int source_web_side_type
        varchar_100_ comment
        int mt4_user
        varchar_100_ mt4_pass
        varchar_100_ data_base_name
        varchar_100_ mt4_live_ip
        varchar_100_ mt4_demo_ip
        int database_port
        varchar_255_ loginDesign
        varchar_10_ regulator
        int parent_id
        tinyint_1_ is_slave_db
        datetime create_time
        datetime update_time
        varchar_100_ operator
    }
    tb_data_source_sg_r {
        int id
        varchar_20_ datasource_key
        varchar_20_ datasource_meta
        int business_id
        varchar_100_ data_name
        varchar_100_ data_ip
        varchar_100_ data_user
        varchar_100_ data_pass
        int status
        int is_del
        varchar_10_ database_type
        int source_web_side_type
        varchar_100_ comment
        int mt4_user
        varchar_100_ mt4_pass
        varchar_100_ data_base_name
        varchar_100_ mt4_live_ip
        varchar_100_ mt4_demo_ip
        int database_port
        varchar_255_ loginDesign
        varchar_10_ regulator
        int parent_id
        tinyint_1_ is_slave_db
        datetime create_time
        datetime update_time
        varchar_100_ operator
    }
    tb_data_source_sg_rw {
        int id
        varchar_20_ datasource_key
        varchar_20_ datasource_meta
        int business_id
        varchar_100_ data_name
        varchar_100_ data_ip
        varchar_100_ data_user
        varchar_100_ data_pass
        int status
        int is_del
        varchar_10_ database_type
        int source_web_side_type
        varchar_100_ comment
        int mt4_user
        varchar_100_ mt4_pass
        varchar_100_ data_base_name
        varchar_100_ mt4_live_ip
        varchar_100_ mt4_demo_ip
        int database_port
        varchar_255_ loginDesign
        varchar_10_ regulator
        int parent_id
        tinyint_1_ is_slave_db
        datetime create_time
        datetime update_time
        varchar_100_ operator
    }
    tb_data_source_type {
        int id
        varchar_100_ description
    }