%% Category: deposit (2 tables)
erDiagram
    tb_deposit_constraints {
        int_unsigned id
        int payment_type
        int payment_channel
        int country_code
        varchar_10_ regulator
        tinyint_1_ is_default
        varchar_10_ currency
        decimal_20_4_ min_amount
        decimal_20_4_ max_amount
        tinyint_1_ is_active
        tinyint_1_ is_del
    }
    tb_deposit_version {
        int id
        varchar_150_ name
    }