%% Category: edit (1 tables)
erDiagram
    tb_edit_sync_email_log {
        int id
        int operate_user
        datetime operate_time
        varchar_255_ user_name
        varchar_1000_ befer_email
        varchar_1000_ after_email
        tinyint_1_ operate_type
        tinyint_1_ syncFlag
    }