%% Category: eodprice (1 tables)
erDiagram
    tb_eodprice_run_status {
        int id
        date eod_price_date
        datetime start_time
        datetime end_time
        int status
        tinyint_1_ is_del
    }