%% Category: error (1 tables)
erDiagram
    tb_error_config {
        int id
        varchar_50_ error_code
        varchar_255_ error_key
        varchar_255_ error_message
        bit_1_ is_del
    }