%% Category: facebook (1 tables)
erDiagram
    tb_facebook_s2s_record {
        int id
        int user_id
        json response_json
        varchar_255_ fbtrace_id
        varchar_255_ fbclick_id
        varchar_255_ event_id
        json custom_data
        varchar_255_ event_id_encoded
        varchar_255_ event_name
        varchar_255_ client_ip_address
        varchar_255_ action_source
        varchar_255_ client_user_agent
        varchar_512_ email
        varchar_512_ phone_number
        varchar_2048_ event_source_url
        timestamp create_time
        timestamp event_epoch_seconds
    }

    %% Cross-category references:
    %% tb_marketing_dashboard_user (external) --> tb_facebook_s2s_record