%% Category: i18n (1 tables)
erDiagram
    tb_i18n {
        bigint id
        varchar_50_ i18n_code
        varchar_255_ i18n_key
        text i18n_value
        varchar_20_ locale
        varchar_100_ module
        varchar_50_ business_domain
        int severity
        tinyint is_del
        varchar_255_ create_by
        varchar_255_ update_by
        datetime created_time
        datetime updated_time
    }