%% Category: indicator (1 tables)
erDiagram
    tb_indicator_info {
        int id
        int indicator_code
        varchar_100_ indicator_name_en
        varchar_1024_ explanation_en
        varchar_100_ indicator_name_cn
        varchar_1024_ explanation_cn
        bigint rule_id
        varchar_512_ rule_name
        int indicator_type
        int sub_indicator_type
        int indicator_dimension
        int eod
        int eom
        int multi_currency
        varchar_50_ data_type
        int sales_kpi_type
        tinyint_1_ status
        int order_num
        varchar_1024_ extra
        datetime create_time
        datetime update_time
        int operator_id
        varchar_1024_ operator
    }

    %% Cross-category references:
    %% tb_match_group_rule (external) --> tb_indicator_info