%% Category: legacy (18 tables)
erDiagram
    old_tb_bybit_balance_record {
        int id
        varchar_16_ balance_date
        varchar_64_ account_type
        varchar_64_ member_id
        varchar_64_ coin
        varchar_64_ wallet_balance
        varchar_64_ transfer_balance
        varchar_64_ bonus
        text request_params
        text response_params
        text shadow_account
        datetime_3_ create_time
        datetime_3_ update_time
        tinyint_1_ is_deleted
    }
    old_tb_bybit_deposit_record {
        int id
        varchar_255_ tx_id
        int type
        varchar_100_ sub_member_id
        varchar_100_ coin
        varchar_255_ chain
        decimal_64_30_ amount
        int status
        varchar_255_ to_address
        varchar_255_ tag
        decimal_64_30_ deposit_fee
        bigint success_at
        decimal_64_30_ confirmations
        varchar_255_ tx_index
        varchar_255_ block_hash
        int batch_release_limit
        int deposit_type
        varchar_255_ transfer_id
        varchar_255_ transfer_address
        bigint transfer_createdTime
        int attribution
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_bybit_exchange_record {
        int id
        varchar_255_ account_type
        varchar_255_ exchange_tx_id
        varchar_255_ user_id
        varchar_100_ from_coin
        varchar_100_ from_coin_type
        varchar_100_ to_coin
        varchar_100_ to_coin_type
        decimal_64_30_ from_amount
        decimal_64_30_ to_amount
        varchar_100_ exchange_status
        varchar_1024_ exchange_info
        decimal_64_30_ convert_rate
        bigint created_at
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_bybit_inter_transfer_record {
        int id
        varchar_255_ transfer_id
        varchar_100_ coin
        decimal_64_30_ amount
        varchar_255_ from_account_type
        varchar_255_ to_account_type
        bigint timestamp
        varchar_100_ status
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_bybit_transfer_record {
        int id
        varchar_255_ transfer_id
        varchar_100_ coin
        decimal_64_30_ amount
        varchar_255_ from_member_id
        varchar_255_ to_member_id
        varchar_255_ from_account_type
        varchar_255_ to_account_type
        bigint timestamp
        varchar_100_ status
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_bybit_withdraw_record {
        int id
        varchar_255_ withdraw_id
        int withdraw_type
        varchar_255_ tx_id
        varchar_100_ coin
        varchar_255_ chain
        decimal_64_30_ amount
        decimal_64_30_ withdraw_fee
        varchar_100_ status
        varchar_255_ to_address
        varchar_255_ tag
        bigint withdraw_createTime
        bigint withdraw_updateTime
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_wallet_account_config {
        int id
        varchar_100_ account_type_code
        varchar_50_ account_type
        varchar_100_ account_type_name
        varchar_50_ asset_type
        varchar_100_ asset_type_name
        datetime create_time
        varchar_255_ create_user
        datetime update_time
        varchar_255_ update_user
    }
    old_tb_wallet_bybit_deposit_record {
        int id
        varchar_255_ tx_id
        int type
        varchar_100_ sub_member_id
        varchar_100_ coin
        varchar_255_ chain
        decimal_64_30_ amount
        int status
        varchar_255_ to_address
        varchar_255_ tag
        decimal_64_30_ deposit_fee
        bigint success_at
        decimal_64_30_ confirmations
        varchar_255_ tx_index
        varchar_255_ block_hash
        int batch_release_limit
        int deposit_type
        varchar_255_ transfer_id
        varchar_255_ transfer_address
        bigint transfer_createdTime
        int attribution
        varchar_255_ data_fingerprint
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_wallet_bybit_exchange_record {
        int id
        varchar_255_ account_type
        varchar_255_ exchange_tx_id
        varchar_255_ user_id
        varchar_100_ from_coin
        varchar_100_ from_coin_type
        varchar_100_ to_coin
        varchar_100_ to_coin_type
        decimal_64_30_ from_amount
        decimal_64_30_ to_amount
        varchar_100_ exchange_status
        varchar_255_ param_type
        varchar_255_ param_value
        decimal_64_30_ convert_rate
        bigint created_at
        int attribution
        varchar_255_ data_fingerprint
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_wallet_bybit_transfer_record {
        int id
        varchar_255_ transfer_id
        varchar_100_ coin
        decimal_64_30_ amount
        varchar_255_ from_member_id
        varchar_255_ to_member_id
        varchar_255_ from_account_type
        varchar_255_ to_account_type
        bigint timestamp
        varchar_100_ status
        int attribution
        varchar_255_ data_fingerprint
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_wallet_bybit_withdraw_record {
        int id
        varchar_255_ withdraw_id
        int withdraw_type
        varchar_255_ tx_id
        varchar_100_ coin
        varchar_255_ chain
        decimal_64_30_ amount
        decimal_64_30_ withdraw_fee
        varchar_100_ status
        varchar_255_ to_address
        varchar_255_ tag
        bigint withdraw_createTime
        bigint withdraw_updateTime
        int attribution
        varchar_255_ data_fingerprint
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_wallet_ingress_app_config {
        int_unsigned id
        varchar_50_ app_key
        varchar_100_ app_name
        varchar_128_ app_secret
        varchar_5_ brand
        varchar_50_ channel_code
        varchar_50_ channel_account_no
        tinyint status
        text ip_whitelist
        varchar_255_ callback_url
        tinyint business_type
        varchar_255_ remark
        datetime_3_ create_time
        bigint creator
        datetime_3_ update_time
        bigint updator
    }
    old_tb_wallet_ingress_request_log {
        bigint_unsigned id
        varchar_50_ request_id
        varchar_50_ app_key
        varchar_50_ task_code
        varchar_50_ withdraw_order_no
        varchar_50_ app_order_no
        varchar_20_ request_type
        datetime_3_ request_time
        datetime_3_ response_time
        varchar_50_ request_url
        varchar_50_ request_ip
        mediumtext request_body
        mediumtext response
        varchar_20_ direction
        tinyint status
        datetime_3_ create_time
        datetime_3_ update_time
    }
    old_tb_wallet_ingress_withdraw_order {
        int_unsigned id
        varchar_50_ app_key
        varchar_50_ withdraw_order_no
        varchar_50_ request_id
        varchar_50_ order_no
        varchar_50_ business_order_id
        bigint user_id
        varchar_256_ withdraw_id
        varchar_512_ tx_id
        varchar_50_ channel_account_id
        varchar_50_ sub_account_id
        varchar_100_ apply_account_no
        varchar_20_ account_type
        varchar_50_ channel_code
        varchar_5_ brand
        varchar_20_ regulator
        varchar_50_ coin
        varchar_20_ chain
        varchar_100_ withdrawal_address
        decimal_32_16_ amount
        int recreate_count
        varchar_255_ notification_url
        int notification_send_count
        int notification_send_status
        datetime notification_time
        varchar_255_ trade_hash
        decimal_32_16_ fee_amt
        varchar_50_ tag
        varchar_50_ country
        varchar_50_ country_code
        varchar_20_ timestamp
        tinyint withdrawal_type
        varchar_12_ ingress_withdraw_type
        tinyint force_chain
        varchar_10_ account_type_withdrawal
        tinyint fee_type
        text beneficiary
        varchar_255_ remark
        tinyint status
        varchar_50_ channel_status
        tinyint asset_account_push_status
        datetime_3_ create_time
        bigint creator
        datetime_3_ update_time
        bigint updator
        bigint operator
        varchar_255_ operation_note
        datetime_3_ transaction_success_time
    }
    old_tb_wallet_projection_account {
        int id
        varchar_100_ account_type_code
        int asset_type
        varchar_100_ asset_account_no
        varchar_100_ currency_type
        varchar_100_ currency
        decimal_64_30_ account_balance
        decimal_64_30_ available_balance
        varchar_255_ channel_code
        varchar_255_ channel_mer_id
        varchar_255_ channel_sub_user_id
        int status
        int is_del
        varchar_100_ brand
        varchar_100_ regulator
        varchar_100_ user_id
        varchar_100_ currency_account_no
        varchar_255_ data_fingerprint
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_wallet_projection_account_daily_statistics {
        int id
        varchar_100_ asset_account_no
        decimal_64_30_ begin_balance
        decimal_64_30_ end_balance
        varchar_100_ currency
        decimal_64_30_ manual_deposit_balance
        decimal_64_30_ business_deposit_balance
        decimal_64_30_ waiting_collection_balance
        decimal_64_30_ manual_withdraw_balance
        decimal_64_30_ business_withdraw_balance
        decimal_64_30_ manual_withdraw_fee
        decimal_64_30_ business_withdraw_fee
        decimal_64_30_ channel_balance
        decimal_64_30_ rate
        datetime statistics_time
        varchar_255_ data_fingerprint
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_wallet_projection_account_record {
        int id
        varchar_100_ asset_account_no
        int account_set_mode
        int transaction_attribution
        int transaction_type
        varchar_255_ channel_record_id
        varchar_255_ wallet_order_id
        int business_type
        decimal_64_30_ occur_amt
        decimal_64_30_ begin_balance
        decimal_64_30_ end_balance
        varchar_100_ currency
        int fee_type
        varchar_255_ chain
        varchar_100_ user_id
        datetime business_handle_time
        datetime channel_time
        datetime channel_handle_time
        datetime channel_create_time
        varchar_255_ data_fingerprint
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }
    old_tb_wallet_reconciliation_exception {
        int id
        int business_type
        varchar_255_ exception_id
        int exception_type
        datetime create_time
        varchar_100_ create_user
        datetime update_time
        varchar_100_ update_user
    }

    %% Cross-category references:
    %% tb_affiliate_cpa_transfer (external) --> old_tb_wallet_bybit_deposit_record
    %% tb_marketing_dashboard_user (external) --> old_tb_wallet_bybit_exchange_record
    %% tb_affiliate_cpa_transfer (external) --> old_tb_bybit_transfer_record
    %% tb_affiliate_cpa_transfer (external) --> old_tb_wallet_bybit_transfer_record
    %% tb_marketing_dashboard_user (external) --> old_tb_wallet_projection_account_record
    %% tb_dap_payment_withdraw (external) --> old_tb_bybit_withdraw_record
    %% tb_marketing_dashboard_user (external) --> old_tb_wallet_projection_account
    %% tb_affiliate_cpa_transfer (external) --> old_tb_bybit_deposit_record
    %% tb_payment_source_exception (external) --> old_tb_wallet_reconciliation_exception
    %% tb_affiliate_cpa_transfer (external) --> old_tb_bybit_inter_transfer_record
    %% tb_dap_payment_withdraw (external) --> old_tb_wallet_bybit_withdraw_record
    %% tb_marketing_dashboard_user (external) --> old_tb_wallet_ingress_withdraw_order
    %% tb_dap_payment_withdraw (external) --> old_tb_wallet_ingress_withdraw_order
    %% tb_marketing_dashboard_user (external) --> old_tb_bybit_exchange_record