%% Category: marketing (1 tables)
erDiagram
    tb_marketing_dashboard_user {
        int id
        int total_first_deposit
        int total_live
        int total_demo
        int total_partner
        int total_app
        decimal_30_4_ new_user_conversion_rate
        date data_day
        int country_code
        varchar_30_ regulator
        datetime create_time
        datetime update_time
        tinyint is_del
    }