%% Category: monitor (1 tables)
erDiagram
    tb_monitor_average_spreads {
        bigint id
        int datasource_id
        varchar_100_ symbol
        decimal_18_6_ average_spread
        date monitor_date
        datetime create_time
    }