%% Category: mt4 (15 tables)
erDiagram
    mt4_old_new_ticket_mapping {
        int id
        varchar_255_ oldTicket
        varchar_255_ newTicket
        int server
    }
    mt4_symbols {
        varchar_255_ Symbol
    }
    mt4_trades_archived_temp {
        int brand
        varchar_150_ DatabaseName
        varchar_32_ brand_name
        int TICKET
        int LOGIN
        char_16_ SYMBOL
        int DIGITS
        int CMD
        int VOLUME
        datetime OPEN_TIME
        double OPEN_PRICE
        double SL
        double TP
        datetime CLOSE_TIME
        datetime EXPIRATION
        int REASON
        double CONV_RATE1
        double CONV_RATE2
        double COMMISSION
        double COMMISSION_AGENT
        double SWAPS
        double CLOSE_PRICE
        double PROFIT
        double TAXES
        char_32_ COMMENT
        int INTERNAL_ID
        double MARGIN_RATE
        int TIMESTAMP
        int MAGIC
        int GW_VOLUME
        int GW_OPEN_PRICE
        int GW_CLOSE_PRICE
        datetime MODIFY_TIME
    }
    mt4_users_archived_temp {
        int brand
        varchar_150_ DatabaseName
        varchar_32_ brand_name
        int LOGIN
        char_16_ GROUP
        int ENABLE
        int ENABLE_CHANGE_PASS
        int ENABLE_READONLY
        int ENABLE_OTP
        char_32_ PASSWORD_PHONE
        char_128_ NAME
        char_32_ COUNTRY
        char_32_ CITY
        char_32_ STATE
        char_16_ ZIPCODE
        char_128_ ADDRESS
        char_32_ LEAD_SOURCE
        char_32_ PHONE
        char_48_ EMAIL
        char_64_ COMMENT
        char_32_ ID
        char_16_ STATUS
        datetime REGDATE
        datetime LASTDATE
        int LEVERAGE
        int AGENT_ACCOUNT
        int TIMESTAMP
        double BALANCE
        double PREVMONTHBALANCE
        double PREVBALANCE
        double CREDIT
        double INTERESTRATE
        double TAXES
        int SEND_REPORTS
        int_unsigned MQID
        int USER_COLOR
        double EQUITY
        double MARGIN
        double MARGIN_LEVEL
        double MARGIN_FREE
        char_16_ CURRENCY
        blob API_DATA
        datetime MODIFY_TIME
    }
    tb_mt4_close {
        int login
        bigint ticket
        int cmd
        char_16_ symbol
        bigint_unsigned volume
        datetime close_time
        double credit
        double equity
        double margin
        double balance
        tinyint trade_on_credit
        int server
        char_32_ comment
        varchar_255_ note
    }
    tb_mt4_group_security {
        int id
        int server
        varchar_128_ group_name
        varchar_128_ security
        int type
        double spread_diff
        int show
        int trade
        int execution
        double comm_base
        int comm_type
        int comm_lots
        double comm_agent
        int comm_agent_type
        int lot_min
        int lot_max
        int lot_step
        int ie_deviation
        int confirmation
        int trade_rights
        int ie_quick_mode
        int auto_close_out_mode
        double comm_tax
        int comm_agent_lots
        int free_margin_mode
        text symbols
        datetime create_time
    }
    tb_mt4_margin {
        bigint_unsigned login
        double margin_level
        int account_level_type
        datetime create_time
        datetime update_time
        int server
    }
    tb_mt4_prices {
        decimal_38_6_ price
        date date
        varchar_64_ serverId
        varchar_32_ symbol
        int id
        datetime update_time
    }
    tb_mt4_prices_backup {
        decimal_38_6_ price
        date date
        varchar_64_ serverId
        varchar_32_ symbol
        int id
    }
    tb_mt4_prices_backup2 {
        decimal_38_6_ price
        date date
        varchar_64_ serverId
        varchar_32_ symbol
        int id
    }
    tb_mt4_prices_bk_230615 {
        decimal_38_6_ price
        date date
        varchar_64_ serverId
        varchar_32_ symbol
        int id
    }
    tb_mt4_prices_copy1 {
        decimal_38_6_ price
        date date
        varchar_64_ serverId
        varchar_32_ symbol
        int id
    }
    tb_mt4_prices_crypto {
        int id
        decimal_38_6_ price
        datetime date
        varchar_32_ serverId
        varchar_32_ symbol
        datetime update_time
    }
    tb_mt4_symbol {
        int id
        int server
        varchar_128_ name
        varchar_1024_ description
        varchar_128_ source
        varchar_128_ currency
        int type
        int digits
        int trade
        bigint background_color
        int count
        int count_original
        int real_time
        int starting
        int expiration
        text sessions
        int profit_mode
        int filter
        int filter_counter
        int filter_limit
        int filter_smoothing
        int logging
        int spread
        double spread_balance
        int exe_mode
        int swap_enable
        int swap_type
        double swap_long
        double swap_short
        int swap_rollover3_days
        double contract_size
        double tick_value
        int tick_size
        int stops_level
        int gtc_pendings
        int margin_mode
        double margin_initial
        double margin_maintenance
        double margin_hedged
        double margin_divider
        double point
        double multiply
        double bid_tick_value
        double ask_tick_value
        int long_only
        double instant_max_volume
        varchar_128_ margin_currency
        int freeze_level
        int margin_hedged_strong
        int value_date
        int quotes_delay
        int swap_open_price
        int swap_variation_margin
        datetime create_time
        varchar_50_ profit_currency
    }
    tb_mt4_trade {
        bigint ticket
        int login
        char_16_ symbol
        int digits
        int cmd
        int volume
        datetime open_time
        double open_price
        double sl
        double tp
        int expiration
        int reason
        double conv_rate
        double commission
        double commission_agent
        double storage
        double profit
        double taxes
        char_32_ comment
        double margin_rate
        int timestamp
        int magic
        int state
        datetime close_time
        int gw_volume
        int gw_open_price
        int gw_order
        double margin
        double equity
        double balance
        double credit
        tinyint trade_on_credit
        tinyint negative_equity
        int server
        char_16_ group
        double bid
        double ask
    }