%% Category: partner (2 tables)
erDiagram
    tb_partner_symbol_whitelist {
        int_unsigned id
        varchar_32_ partner
        varchar_32_ partner_symbol
        varchar_32_ symbol
        tinyint is_del
        varchar_128_ create_by
        varchar_128_ update_by
        datetime date_created
        datetime date_updated
    }
    tb_partner_task {
        int_unsigned id
        varchar_32_ partner
        varchar_16_ status
        varchar_16_ task_type
        datetime start_time
        datetime end_time
        int period
        varchar_19_ task_time
        tinyint is_del
        datetime date_created
        datetime date_updated
    }