%% Category: province (1 tables)
erDiagram
    tb_province {
        int ProvinceID
        varchar_50_ ProvinceName
        varchar_50_ ProvinceName_en
        datetime DateCreated
        datetime DateUpdated
        int CountryID
        varchar_50_ province_code
        tinyint_3__unsigned_zerofill is_del
        varchar_50_ operator
    }