%% Category: remote (1 tables)
erDiagram
    tb_remote_intercept_strategy {
        int id
        int type
        varchar_255_ intercept_type
        int strategy_type
        varchar_255_ field
        datetime update_time
        int update_user_id
        varchar_255_ update_user_name
        int status
    }