%% Category: sec (6 tables)
erDiagram
    tb_sec_apply_auth_record {
        bigint_unsigned id
        bigint user_id
        varchar_64_ src_id
        varchar_64_ business_code
        varchar_16_ business_type
        varchar_128_ mobile
        varchar_255_ email
        varchar_2_ country_code
        varchar_255_ phone_code
        varchar_128_ business_id
        int risk_advice
        int risk_level
        bigint apply_expiration
        varchar_32_ sub_business_type
        varchar_255_ device_id
        varchar_255_ base_auth_config
        varchar_255_ next_verify_config
        varchar_255_ verify_track_config
        varchar_255_ valid_verify_config
        varchar_255_ forward_url
        varchar_16_ refuse_code
        varchar_255_ refuse_reason
        varchar_32_ brand
        varchar_16_ login_mode
        varchar_32_ regular
        varchar_64_ request_ip
        bigint create_time
        bigint update_time
        varchar_255_ fail_url
        text link_data
    }
    tb_sec_auth_blacklist {
        bigint_unsigned id
        varchar_64_ src_id
        bigint user_id
        varchar_64_ business_code
        bigint valid_time
        varchar_32_ risk_code
        varchar_255_ risk_config
        varchar_255_ risk_reason
        bigint create_time
        bigint update_time
        varchar_32_ brand
        varchar_32_ regular
        varchar_16_ business_type
        tinyint_1_ status
    }
    tb_sec_auth_config {
        bigint_unsigned id
        varchar_64_ business_code
        varchar_32_ business_type
        varchar_32_ brand
        varchar_32_ regular
        varchar_32_ sub_business_type
        tinyint_1_ auth_switch_config
        tinyint_1_ allow_client_auth_enabled
        varchar_255_ base_auth_config
        varchar_255_ other_config
        bigint update_user_id
        bigint business_valid_mins_time
        bigint create_time
        bigint update_time
        int config_priority
    }
    tb_sec_auth_detail {
        bigint_unsigned id
        varchar_64_ src_id
        varchar_16_ verify_type
        varchar_64_ verify_code
        varchar_16_ business_type
        varchar_1024_ login_token
        varchar_128_ request_ip
        varchar_255_ device_finger
        tinyint_1_ auth_status
        int left_auth_time
        bigint verify_time
        varchar_16_ fail_code
        varchar_255_ fail_reason
        varchar_255_ client_session_id
        bigint create_time
        bigint update_time
    }
    tb_sec_auth_limitation {
        bigint id
        varchar_32_ brand
        varchar_16_ regular
        varchar_32_ business_code
        varchar_16_ business_type
        char_2_ operation
        int time_window
        int max_count
        varchar_50_ impl
        varchar_255_ warning
    }
    tb_sec_verification_code_record {
        bigint id
        varchar_64_ src_id
        varchar_16_ business_type
        varchar_16_ verify_type
        tinyint_1_ send_status
        bigint request_time
        varchar_255_ client_session_id
        varchar_1024_ login_token
        varchar_128_ request_ip
        varchar_255_ device_finger
        varchar_50_ fail_code
        varchar_500_ fail_reason
        int left_send_time
        bigint create_time
        bigint update_time
        varchar_255_ verify_account
        varchar_64_ business_code
        varchar_255_ template_code
        tinyint verify_status
    }

    %% Cross-category references:
    %% tb_marketing_dashboard_user (external) --> tb_sec_apply_auth_record
    %% tb_marketing_dashboard_user (external) --> tb_sec_auth_blacklist