%% Category: stock (1 tables)
erDiagram
    tb_stock {
        bigint id
        varchar_40_ user_id
        int activity_id
        varchar_10_ stock_name
        varchar_10_ stock_symbol
        varchar_10_ currency
        varchar_30_ order
        decimal_25_10_ volume
        datetime open_time
        datetime close_time
        decimal_20_10_ profit
        varchar_1_ stock_status
        varchar_1_ stock_unlock_status
        int stock_unlock_volume
        int status_code
        varchar_50_ login
        varchar_10_ login_currency
        datetime create_time
        datetime update_time
        int stock_unlock_target_volume
        varchar_40_ reward_value
        bigint user_coupon_id
        datetime expire_time
        datetime mts_trade_query_time
        varchar_10_ margin_currency
        decimal_25_10_ contract_size
    }

    %% Cross-category references:
    %% tb_marketing_dashboard_user (external) --> tb_stock
    %% tb_salary_activity (external) --> tb_stock
    %% tb_user_coupon (external) --> tb_stock