%% Category: switch (1 tables)
erDiagram
    tb_switch_bonus_info {
        int id
        int user_id
        int cpa_id
        varchar_255_ name
        varchar_255_ email
        varchar_255_ phone
        varchar_255_ phone_code
        tinyint source
        varchar_255_ relation_user
        varchar_255_ business_number
        tinyint registered
        tinyint register_type
        datetime create_time
        datetime update_time
    }

    %% Cross-category references:
    %% tb_marketing_dashboard_user (external) --> tb_switch_bonus_info
    %% tb_cpa_allot_cr_cpa (external) --> tb_switch_bonus_info