%% Category: third (1 tables)
erDiagram
    tb_third_party_data {
        int id
        int user_id
        varchar_255_ fbclick_id
        datetime create_time
        varchar_255_ taboola_clickid
    }

    %% Cross-category references:
    %% tb_marketing_dashboard_user (external) --> tb_third_party_data