%% Category: upgrade (1 tables)
erDiagram
    tb_upgrade_ib_org_set {
        int id
        int org_id
        datetime create_time
        datetime update_time
        varchar_255_ create_by
        varchar_255_ update_by
        tinyint is_del
    }

    %% Cross-category references:
    %% tb_commission_package_org (external) --> tb_upgrade_ib_org_set